# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2023-11-14 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("ext_gestaltmatcher", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="SmallVariantQueryPediaScores",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("gene_id", models.CharField(help_text="Entrez gene ID", max_length=64)),
                ("gene_symbol", models.CharField(help_text="The gene symbol", max_length=128)),
                ("score", models.FloatField(help_text="The gene score")),
                (
                    "query",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="variants.SmallVariantQuery"
                    ),
                ),
            ],
        )
    ]
