# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-19 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("hgmd", "0002_auto_20190425_1523")]

    operations = [
        migrations.AddField(
            model_name="hgmdpubliclocus",
            name="bin",
            field=models.IntegerField(default=-1),
            preserve_default=False,
        )
    ]
