# Generated by Django 3.2.25 on 2024-05-15 11:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hgmd", "0004_auto_20190830_1126"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HgmdPublicLocus",
        ),
    ]
