# Generated by Django 3.2.24 on 2024-02-27 13:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("svs", "0023_int_to_bigint"),
    ]

    operations = [
        migrations.RunSQL(
            r"""TRUNCATE TABLE "svs_svquery" CASCADE""",
            "",
        )
    ]
