# Generated by Django 3.2.25 on 2024-08-07 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("svs", "0027_auto_20240529_1403"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="buildbackgroundsvsetjob",
            options={"ordering": ("-date_created", "pk")},
        ),
        migrations.AlterModelOptions(
            name="cleanupbackgroundsvsetjob",
            options={"ordering": ("-date_created", "pk")},
        ),
        migrations.AlterModelOptions(
            name="svquery",
            options={"ordering": ("-date_created", "pk")},
        ),
        migrations.AlterModelOptions(
            name="svqueryresultset",
            options={"ordering": ("-date_created", "pk")},
        ),
    ]
