# Generated by Django 4.2.16 on 2024-10-07 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bgjobs", "0001_squashed_0006_auto_20200526_1657"),
        ("svs", "0028_auto_20240807_0850"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buildbackgroundsvsetjob",
            name="bg_job",
            field=models.ForeignKey(
                help_text="Background job for state etc.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                to="bgjobs.backgroundjob",
            ),
        ),
        migrations.AlterField(
            model_name="cleanupbackgroundsvsetjob",
            name="bg_job",
            field=models.ForeignKey(
                help_text="Background job for state etc.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                to="bgjobs.backgroundjob",
            ),
        ),
        migrations.AlterField(
            model_name="importstructuralvariantbgjob",
            name="bg_job",
            field=models.ForeignKey(
                help_text="Background job for state etc.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_related",
                to="bgjobs.backgroundjob",
            ),
        ),
        migrations.AlterField(
            model_name="svquery",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the query",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_related",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
