# Generated by Django 3.2.21 on 2023-09-20 06:08

import uuid

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_pydantic_field._migration_serializers
import django_pydantic_field.fields

import cases_qc.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("variants", "0095_auto_20230724_0820"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseQc",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sodar_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "state",
                    models.CharField(
                        choices=[("DRAFT", "DRAFT"), ("ACTIVE", "ACTIVE")],
                        default="DRAFT",
                        max_length=50,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="variants.case"
                    ),
                ),
            ],
            options={
                "ordering": ["-date_created"],
            },
        ),
        migrations.CreateModel(
            name="WgsHistMetrics",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sodar_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("sample", models.CharField(max_length=200)),
                (
                    "keys",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200), max_length=10000, size=None
                    ),
                ),
                (
                    "values",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), max_length=10000, size=None
                    ),
                ),
                (
                    "caseqc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cases_qc.caseqc"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WgsFineHist",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sodar_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("sample", models.CharField(max_length=200)),
                (
                    "keys",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), max_length=10000, size=None
                    ),
                ),
                (
                    "values",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), max_length=10000, size=None
                    ),
                ),
                (
                    "caseqc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cases_qc.caseqc"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WgsCoverageMetrics",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sodar_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("sample", models.CharField(max_length=200)),
                (
                    "metrics",
                    django_pydantic_field.fields.PydanticSchemaField(
                        config=None,
                        schema=django_pydantic_field._migration_serializers.GenericContainer(
                            list, (cases_qc.models.DragenStyleMetric,)
                        ),
                    ),
                ),
                (
                    "caseqc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cases_qc.caseqc"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WgsContigMeanCovMetrics",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sodar_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("sample", models.CharField(max_length=200)),
                (
                    "metrics",
                    django_pydantic_field.fields.PydanticSchemaField(
                        config=None,
                        schema=django_pydantic_field._migration_serializers.GenericContainer(
                            list, (cases_qc.models.DragenStyleCoverage,)
                        ),
                    ),
                ),
                (
                    "caseqc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cases_qc.caseqc"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VcMetrics",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sodar_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("sample", models.CharField(max_length=200)),
                (
                    "metrics",
                    django_pydantic_field.fields.PydanticSchemaField(
                        config=None,
                        schema=django_pydantic_field._migration_serializers.GenericContainer(
                            list, (cases_qc.models.DragenStyleMetric,)
                        ),
                    ),
                ),
                (
                    "caseqc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cases_qc.caseqc"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VcHethomRatioMetrics",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sodar_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("sample", models.CharField(max_length=200)),
                (
                    "metrics",
                    django_pydantic_field.fields.PydanticSchemaField(
                        config=None,
                        schema=django_pydantic_field._migration_serializers.GenericContainer(
                            list, (cases_qc.models.DragenStyleMetric,)
                        ),
                    ),
                ),
                (
                    "caseqc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cases_qc.caseqc"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TrimmerMetrics",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sodar_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("sample", models.CharField(max_length=200)),
                (
                    "metrics",
                    django_pydantic_field.fields.PydanticSchemaField(
                        config=None,
                        schema=django_pydantic_field._migration_serializers.GenericContainer(
                            list, (cases_qc.models.DragenStyleMetric,)
                        ),
                    ),
                ),
                (
                    "caseqc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cases_qc.caseqc"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TimeMetrics",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sodar_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("sample", models.CharField(max_length=200)),
                (
                    "metrics",
                    django_pydantic_field.fields.PydanticSchemaField(
                        config=None,
                        schema=django_pydantic_field._migration_serializers.GenericContainer(
                            list, (cases_qc.models.DragenStyleMetric,)
                        ),
                    ),
                ),
                (
                    "caseqc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cases_qc.caseqc"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SvMetrics",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sodar_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("sample", models.CharField(max_length=200)),
                (
                    "metrics",
                    django_pydantic_field.fields.PydanticSchemaField(
                        config=None,
                        schema=django_pydantic_field._migration_serializers.GenericContainer(
                            list, (cases_qc.models.DragenStyleMetric,)
                        ),
                    ),
                ),
                (
                    "caseqc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cases_qc.caseqc"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RohMetrics",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sodar_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("sample", models.CharField(max_length=200)),
                (
                    "metrics",
                    django_pydantic_field.fields.PydanticSchemaField(
                        config=None,
                        schema=django_pydantic_field._migration_serializers.GenericContainer(
                            list, (cases_qc.models.DragenStyleMetric,)
                        ),
                    ),
                ),
                (
                    "caseqc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cases_qc.caseqc"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PloidyEstimationMetrics",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sodar_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("sample", models.CharField(max_length=200)),
                (
                    "metrics",
                    django_pydantic_field.fields.PydanticSchemaField(
                        config=None,
                        schema=django_pydantic_field._migration_serializers.GenericContainer(
                            list, (cases_qc.models.DragenStyleMetric,)
                        ),
                    ),
                ),
                (
                    "caseqc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cases_qc.caseqc"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MappingMetrics",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sodar_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("sample", models.CharField(max_length=200)),
                (
                    "metrics",
                    django_pydantic_field.fields.PydanticSchemaField(
                        config=None,
                        schema=django_pydantic_field._migration_serializers.GenericContainer(
                            list, (cases_qc.models.DragenStyleMetric,)
                        ),
                    ),
                ),
                (
                    "caseqc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cases_qc.caseqc"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FragmentLengthHistogram",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sodar_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("sample", models.CharField(max_length=200)),
                (
                    "keys",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), max_length=10000, size=None
                    ),
                ),
                (
                    "values",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), max_length=10000, size=None
                    ),
                ),
                (
                    "caseqc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cases_qc.caseqc"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CnvMetrics",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sodar_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("sample", models.CharField(max_length=200)),
                (
                    "metrics",
                    django_pydantic_field.fields.PydanticSchemaField(
                        config=None,
                        schema=django_pydantic_field._migration_serializers.GenericContainer(
                            list, (cases_qc.models.DragenStyleMetric,)
                        ),
                    ),
                ),
                (
                    "caseqc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cases_qc.caseqc"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
