# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-06 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("geneinfo", "0001_initial")]

    operations = [
        migrations.AddIndex(
            model_name="hgnc",
            index=models.Index(fields=["entrez_id"], name="geneinfo_hg_entrez__91b58b_idx"),
        )
    ]
