# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-04 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("geneinfo", "0016_mgimapping_index")]

    operations = [
        migrations.AddIndex(
            model_name="exacconstraints",
            index=models.Index(
                fields=["ensembl_transcript_id"], name="geneinfo_ex_ensembl_40f907_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gnomadconstraints",
            index=models.Index(fields=["ensembl_gene_id"], name="geneinfo_gn_ensembl_561533_idx"),
        ),
    ]
