"""Factory defaults for seqvars query settings."""

from seqvars.models import QueryPresetsFrequency

#: Frequency Preset "any"
FREQUENCY_ANY = QueryPresetsFrequency(
    rank=0,
    label="any",
    gnomad_exomes_enabled=False,
    gnomad_exomes_frequency=None,
    gnomad_exomes_heterozygous=None,
    gnomad_exomes_homozygous=None,
    gnomad_exomes_hemizygous=None,
    gnomad_genomes_enabled=False,
    gnomad_genomes_frequency=None,
    gnomad_genomes_heterozygous=None,
    gnomad_genomes_homozygous=None,
    gnomad_genomes_hemizygous=None,
    inhouse_enabled=False,
    inhouse_carriers=None,
    inhouse_heterozygous=None,
    inhouse_homozygous=None,
    inhouse_hemizygous=None,
    helixmtdb_enabled=False,
    helixmtdb_het_count=None,
    helixmtdb_hom_count=None,
    helixmtdb_frequency=None,
)
#: Frequency Preset "dominant super strict"
FREQUENCY_DOMINANT_SUPER_STRICT = QueryPresetsFrequency(
    rank=1,
    label="dominant super strict",
    gnomad_exomes_enabled=True,
    gnomad_exomes_frequency=0.002,
    gnomad_exomes_heterozygous=1,
    gnomad_exomes_homozygous=0,
    gnomad_exomes_hemizygous=None,
    gnomad_genomes_enabled=True,
    gnomad_genomes_frequency=0.002,
    gnomad_genomes_heterozygous=1,
    gnomad_genomes_homozygous=0,
    gnomad_genomes_hemizygous=None,
    inhouse_enabled=True,
    inhouse_carriers=20,
    inhouse_heterozygous=1,
    inhouse_homozygous=None,
    inhouse_hemizygous=None,
    helixmtdb_enabled=False,
    helixmtdb_het_count=None,
    helixmtdb_hom_count=None,
    helixmtdb_frequency=None,
)
#: Frequency Preset "dominant strict"
FREQUENCY_DOMINANT_STRICT = QueryPresetsFrequency(
    rank=2,
    label="dominant strict",
    gnomad_exomes_enabled=True,
    gnomad_exomes_frequency=0.002,
    gnomad_exomes_heterozygous=1,
    gnomad_exomes_homozygous=0,
    gnomad_exomes_hemizygous=None,
    gnomad_genomes_enabled=True,
    gnomad_genomes_frequency=0.002,
    gnomad_genomes_heterozygous=1,
    gnomad_genomes_homozygous=0,
    gnomad_genomes_hemizygous=None,
    inhouse_enabled=True,
    inhouse_carriers=20,
    inhouse_heterozygous=1,
    inhouse_homozygous=None,
    inhouse_hemizygous=None,
    helixmtdb_enabled=False,
    helixmtdb_het_count=None,
    helixmtdb_hom_count=None,
    helixmtdb_frequency=None,
)
#: Frequency Preset "recessive relaxed"
FREQUENCY_DOMINANT_RELAXED = QueryPresetsFrequency(
    rank=3,
    label="dominant relaxed",
    gnomad_exomes_enabled=True,
    gnomad_exomes_frequency=0.002,
    gnomad_exomes_heterozygous=1,
    gnomad_exomes_homozygous=0,
    gnomad_exomes_hemizygous=None,
    gnomad_genomes_enabled=True,
    gnomad_genomes_frequency=0.002,
    gnomad_genomes_heterozygous=1,
    gnomad_genomes_homozygous=0,
    gnomad_genomes_hemizygous=None,
    inhouse_enabled=True,
    inhouse_carriers=20,
    inhouse_heterozygous=1,
    inhouse_homozygous=None,
    inhouse_hemizygous=None,
    helixmtdb_enabled=False,
    helixmtdb_het_count=None,
    helixmtdb_hom_count=None,
    helixmtdb_frequency=None,
)
#: Frequency Preset "recessive strict"
FREQUENCY_RECESSIVE_STRICT = QueryPresetsFrequency(
    rank=4,
    label="recessive strict",
    gnomad_exomes_enabled=True,
    gnomad_exomes_frequency=0.002,
    gnomad_exomes_heterozygous=1,
    gnomad_exomes_homozygous=0,
    gnomad_exomes_hemizygous=None,
    gnomad_genomes_enabled=True,
    gnomad_genomes_frequency=0.002,
    gnomad_genomes_heterozygous=1,
    gnomad_genomes_homozygous=0,
    gnomad_genomes_hemizygous=None,
    inhouse_enabled=True,
    inhouse_carriers=20,
    inhouse_heterozygous=1,
    inhouse_homozygous=None,
    inhouse_hemizygous=None,
    helixmtdb_enabled=False,
    helixmtdb_het_count=None,
    helixmtdb_hom_count=None,
    helixmtdb_frequency=None,
)
#: Frequency Preset "recessive relaxed"
FREQUENCY_RECESSIVE_RELAXED = QueryPresetsFrequency(
    rank=5,
    label="recessive relaxed",
    gnomad_exomes_enabled=True,
    gnomad_exomes_frequency=0.002,
    gnomad_exomes_heterozygous=1,
    gnomad_exomes_homozygous=0,
    gnomad_exomes_hemizygous=None,
    gnomad_genomes_enabled=True,
    gnomad_genomes_frequency=0.002,
    gnomad_genomes_heterozygous=1,
    gnomad_genomes_homozygous=0,
    gnomad_genomes_hemizygous=None,
    inhouse_enabled=True,
    inhouse_carriers=20,
    inhouse_heterozygous=1,
    inhouse_homozygous=None,
    inhouse_hemizygous=None,
    helixmtdb_enabled=False,
    helixmtdb_het_count=None,
    helixmtdb_hom_count=None,
    helixmtdb_frequency=None,
)
