# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-19 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("clinvar", "0002_clinvarpathogenicgenes")]

    operations = [
        migrations.RemoveIndex(model_name="clinvar", name="clinvar_cli_release_457ca8_idx"),
        migrations.RemoveField(model_name="clinvar", name="position"),
        migrations.RemoveField(model_name="clinvar", name="stop"),
        migrations.AddField(
            model_name="clinvar",
            name="bin",
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clinvar",
            name="end",
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="clinvar",
            index=models.Index(
                fields=["release", "chromosome", "start", "reference", "alternative"],
                name="clinvar_cli_release_1f6a94_idx",
            ),
        ),
    ]
