# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-11 17:19
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinvar", "0004_delete_clinvar"),
    ]

    operations = [
        migrations.CreateModel(
            name="Clinvar",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("release", models.CharField(max_length=32)),
                ("chromosome", models.CharField(max_length=32)),
                ("start", models.IntegerField()),
                ("end", models.IntegerField()),
                ("bin", models.IntegerField()),
                ("reference", models.CharField(max_length=512)),
                ("alternative", models.CharField(max_length=512)),
                ("variation_type", models.CharField(max_length=16)),
                (
                    "symbols",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=32), size=None
                    ),
                ),
                (
                    "hgnc_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=32), size=None
                    ),
                ),
                (
                    "vcv",
                    models.CharField(max_length=32),
                ),
                ("point_rating", models.IntegerField()),
                ("pathogenicity", models.CharField(max_length=128)),
                ("review_status", models.CharField(max_length=128)),
                ("pathogenicity_summary", models.CharField(max_length=128)),
                ("details", models.JSONField()),
            ],
        ),
        migrations.AddIndex(
            model_name="clinvar",
            index=models.Index(
                fields=["release", "chromosome", "start", "reference", "alternative"],
                name="clinvar_cli_release_1f6a94_idx",
            ),
        ),
    ]
