# Generated by Django 3.2.15 on 2022-09-08 14:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinvar", "0008_auto_20220829_1132"),
    ]

    operations = [
        migrations.RemoveField(model_name="clinvar", name="gold_stars",),
        migrations.RemoveField(model_name="clinvar", name="origin",),
        migrations.RemoveField(model_name="clinvar", name="pathogenicity",),
        migrations.RemoveField(model_name="clinvar", name="rcv",),
        migrations.RemoveField(model_name="clinvar", name="review_status",),
        migrations.RemoveField(model_name="clinvar", name="variation_id",),
        migrations.AddField(
            model_name="clinvar",
            name="clinvar_version",
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="clinvar", name="set_type", field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="clinvar",
            name="summary_clinvar_gold_stars",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="clinvar",
            name="summary_clinvar_pathogenicity",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=32), null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="clinvar",
            name="summary_clinvar_pathogenicity_label",
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="clinvar",
            name="summary_clinvar_review_status_label",
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="clinvar",
            name="summary_paranoid_gold_stars",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="clinvar",
            name="summary_paranoid_pathogenicity",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=32), null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="clinvar",
            name="summary_paranoid_pathogenicity_label",
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="clinvar",
            name="summary_paranoid_review_status_label",
            field=models.CharField(max_length=512, null=True),
        ),
    ]
