# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-16 14:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations

operations = []


if not settings.IS_TESTING:
    operations.append(
        migrations.RunSQL(
            """
            DROP MATERIALIZED VIEW IF EXISTS clinvar_clinvarpathogenicgenes;

            CREATE MATERIALIZED VIEW clinvar_clinvarpathogenicgenes
            AS
                SELECT
                    ROW_NUMBER() OVER () AS id,
                    symbol,
                    geneinfo_hgnc.ensembl_gene_id,
                    geneinfo_refseqtohgnc.entrez_id,
                    pathogenic_count,
                    likely_pathogenic_count
                FROM (
                    SELECT
                        unnest(symbols) as symbol,
                        SUM(CASE WHEN summary_clinvar_pathogenicity @> ARRAY['pathogenic'::varchar] THEN 1 ELSE 0 END) AS pathogenic_count,
                        SUM(CASE WHEN summary_clinvar_pathogenicity @> ARRAY['likely pathogenic'::varchar] THEN 1 ELSE 0 END) AS likely_pathogenic_count
                    FROM clinvar_clinvar
                    GROUP BY symbol
                    HAVING
                        SUM(CASE WHEN summary_clinvar_pathogenicity @> ARRAY['pathogenic'::varchar] THEN 1 ELSE 0 END) > 0 OR
                        SUM(CASE WHEN summary_clinvar_pathogenicity @> ARRAY['likely pathogenic'::varchar] THEN 1 ELSE 0 END) > 0
                ) AS clinvar_pathogenic_counts
                LEFT OUTER JOIN geneinfo_hgnc USING (symbol)
                LEFT OUTER JOIN geneinfo_refseqtohgnc USING (hgnc_id)
            WITH DATA;
            """,
            """
            DROP MATERIALIZED VIEW clinvar_clinvarpathogenicgenes;
            """,
        )
    )


class Migration(migrations.Migration):
    dependencies = [
        ("clinvar", "0009_auto_20220908_1430"),
        ("geneinfo", "0005_auto_20190104_1554"),
        ("geneinfo", "0007_refseqtohgnc"),
    ]
    operations = operations
