# Generated by Django 3.2.16 on 2022-10-28 06:57

import uuid

from django.db import migrations, models
import django.db.models.deletion

import varfish.utils


class Migration(migrations.Migration):

    dependencies = [
        ("clinvar_export", "0003_auto_20211129_1443"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="clinvar_error_report",
            field=varfish.utils.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="clinvar_submitter_report",
            field=varfish.utils.JSONField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name="ClinVarReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "sodar_uuid",
                    models.UUIDField(default=uuid.uuid4, help_text="SODAR UUID", unique=True),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("error_report", "error_report"),
                            ("submitter_report", "submitter_report"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, help_text="DateTime of creation"),
                ),
                (
                    "date_modified",
                    models.DateTimeField(auto_now=True, help_text="DateTime of last modification"),
                ),
                ("source_url", models.CharField(max_length=256)),
                ("payload_md5", models.CharField(max_length=32)),
                ("payload", models.TextField()),
                (
                    "submission_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinvar_export.submissionset",
                    ),
                ),
            ],
        ),
    ]
