# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-30 11:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bgjobs", "0003_backgroundjob_date_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="backgroundjob",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="background_jobs",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        )
    ]
