# Generated by Django 3.2.23 on 2024-02-08 16:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("extra_annos", "0004_alter_extraanno_anno_data"),
    ]

    operations = [
        migrations.RunSQL(
            r"""ALTER TABLE "extra_annos_extraanno" ALTER COLUMN "id" TYPE bigint USING "id"::bigint""",
            r"""ALTER TABLE "extra_annos_extraanno" ALTER COLUMN "id" TYPE integer USING "id"::integer""",
        ),
    ]
