version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/conf.py

formats:
  - pdf
  - epub

python:
   install:
     - requirements: docs_manual/requirements.txt
