[tool.coverage.run]
relative_files = true
omit = [
    "varfish/_version.py",
    "*migrations*",
    "*tests*",
]

[tool.coverage.report]
exclude_lines = [
    # Re-enable standard pragma
    "pragma: no cover",
    # Ignore repr() builtin definition, mostly useful for debug code anway
    "def __repr__",
    # Ignore the __main__ entry points
    "if __name__ == '__main__':",
    # Ignore abstract function bodies
    "raise NotImplementedError",
]

[tool.flake8]
exclude = [
    "docs",
    "tests",
    ".*.py",
    "wrapper.py",
    "versioneer.py",
    "docs_manual/src",
    "src",
    "varfish/vueapp/node_modules",
]
max-complexity = 18
select = ["B","C","E","F","W","T4","B9"]
ignore = ["E203","E266","E501","W503"]
max-line-length = 100
per-file-ignores = [
    "tests/**/*.py:E501",
    "docs/conf.py:ALL",
    "config/settings/*.py:F401,F403,F405",
]
import-order-style = "google"

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 100

[tool.pytest.ini_options]
env = [
    "DJANGO_SETTINGS_MODULE=config.settings.test",
]
