# Generated by Django 4.2.16 on 2024-10-07 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cohorts", "0007_alter_cohort_cases"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cohort",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the cohorts",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_related",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
