# Generated by Django 3.2.20 on 2023-07-14 13:25

import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("variants", "0094_case_case_version"),
        ("seqmeta", "0003_targetbedfile_seqmeta_tar_file_ur_9f92c4_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pedigree",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sodar_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pedigree_obj",
                        to="variants.case",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Individual",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sodar_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                (
                    "sex",
                    models.CharField(
                        choices=[
                            ("unknown", "unknown"),
                            ("male", "male"),
                            ("female", "female"),
                            ("other", "other"),
                        ],
                        max_length=128,
                    ),
                ),
                (
                    "karyotypic_sex",
                    models.CharField(
                        choices=[
                            ("unknown", "unknown"),
                            ("XX", "XX"),
                            ("XY", "XY"),
                            ("XO", "XO"),
                            ("XXY", "XXY"),
                            ("XXX", "XXX"),
                            ("XXYY", "XXYY"),
                            ("XXXY", "XXXY"),
                            ("XXXX", "XXXX"),
                            ("XYY", "XYY"),
                            ("other", "other"),
                        ],
                        max_length=128,
                    ),
                ),
                (
                    "assay",
                    models.CharField(
                        blank=True,
                        choices=[("panel_seq", "panel_seq"), ("wes", "wes"), ("wgs", "wgs")],
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "enrichmentkit",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="seqmeta.enrichmentkit",
                    ),
                ),
                (
                    "pedigree",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cases.pedigree"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PhenotypicFeature",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sodar_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("term_id", models.CharField(max_length=128)),
                ("term_label", models.CharField(max_length=128)),
                ("excluded", models.BooleanField(default=False)),
                (
                    "individual",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cases.individual"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("individual", "term_id")},
            },
        ),
        migrations.CreateModel(
            name="Disease",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sodar_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("term_id", models.CharField(max_length=128)),
                ("term_label", models.CharField(max_length=128)),
                ("excluded", models.BooleanField(default=False)),
                (
                    "individual",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cases.individual"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("individual", "term_id")},
            },
        ),
    ]
