from django.urls import path

from variants import views
from variants.urls.annos import annos_ajax_urlpatterns
from variants.urls.presets import presets_ajax_urlpatterns
from variants.views import ajax as views_ajax
from variants.views import api as views_api

app_name = "variants"
ui_urlpatterns = [
    # Views for Case
    path(
        "<uuid:project>/case-delete-job/detail/<uuid:job>/",
        view=views.CaseDeleteJobDetailView.as_view(),
        name="case-delete-job-detail",
    ),
    # View for list background jobs
    path(
        "<uuid:project>/jobs/list/<uuid:case>/",
        view=views.BackgroundJobListView.as_view(),
        name="job-list",
    ),
    # Views for project sync jobs.
    path(
        "<uuid:project>/sync-job/<uuid:job>/",
        view=views.SyncJobDetailView.as_view(),
        name="sync-job-detail",
    ),
    # Views for variants import job.
    path(
        "<uuid:project>/import/<uuid:job>/",
        view=views.ImportVariantsJobDetailView.as_view(),
        name="import-job-detail",
    ),
    # Views for single-case file export jobs.
    path(
        "<uuid:project>/export-job/detail/<uuid:job>/",
        view=views.ExportFileJobDetailView.as_view(),
        name="export-job-detail",
    ),
    path(
        "<uuid:project>/export-job/resubmit/<uuid:job>/",
        view=views.ExportFileJobResubmitView.as_view(),
        name="export-job-resubmit",
    ),
    path(
        "<uuid:project>/export-job/download/<uuid:job>/",
        view=views.ExportFileJobDownloadView.as_view(),
        name="export-job-download",
    ),
    # Views for project-wide cases file export jobs.
    path(
        "<uuid:project>/project-cases-export-job/detail/<uuid:job>/",
        view=views.ExportProjectCasesFileJobDetailView.as_view(),
        name="project-cases-export-job-detail",
    ),
    path(
        "<uuid:project>/project-cases-export-job/resubmit/<uuid:job>/",
        view=views.ExportProjectCasesFileJobResubmitView.as_view(),
        name="project-cases-export-job-resubmit",
    ),
    path(
        "<uuid:project>/project-cases-export-job/download/<uuid:job>/",
        view=views.ExportProjectCasesFileJobDownloadView.as_view(),
        name="project-cases-export-job-download",
    ),
    # Views for MutationDistiller submission jobs
    path(
        "<uuid:project>/distiller-job/detail/<uuid:job>/",
        view=views.DistillerSubmissionJobDetailView.as_view(),
        name="distiller-job-detail",
    ),
    path(
        "<uuid:project>/distiller-job/resubmit/<uuid:job>/",
        view=views.DistillerSubmissionJobResubmitView.as_view(),
        name="distiller-job-resubmit",
    ),
    # Views for CADD submission jobs
    path(
        "<uuid:project>/cadd-job/detail/<uuid:job>/",
        view=views.CaddSubmissionJobDetailView.as_view(),
        name="cadd-job-detail",
    ),
    path(
        "<uuid:project>/cadd-job/resubmit/<uuid:job>/",
        view=views.CaddSubmissionJobResubmitView.as_view(),
        name="cadd-job-resubmit",
    ),
    # Views for SPANR submission jobs
    path(
        "<uuid:project>/spanr-job/detail/<uuid:job>/",
        view=views.SpanrSubmissionJobDetailView.as_view(),
        name="spanr-job-detail",
    ),
    path(
        "<uuid:project>/spanr-job/resubmit/<uuid:job>/",
        view=views.SpanrSubmissionJobResubmitView.as_view(),
        name="spanr-job-resubmit",
    ),
    # Views for Project-wide Statistics Computation submission jobs
    path(
        "<uuid:project>/project-stats-job/detail/<uuid:job>/",
        view=views.ProjectStatsJobDetailView.as_view(),
        name="project-stats-job-detail",
    ),
    # Views for filtering and storing case query results jobs
    path(
        "<uuid:project>/filter-job/detail/<uuid:job>/",
        view=views.FilterJobDetailView.as_view(),
        name="filter-job-detail",
    ),
    path(
        "<uuid:project>/filter-job/resubmit/<uuid:job>/",
        view=views.FilterJobResubmitView.as_view(),
        name="filter-job-resubmit",
    ),
    # Views for filtering and storing project cases query results jobs
    path(
        "<uuid:project>/project-cases-filter-job/detail/<uuid:job>/",
        view=views.ProjectCasesFilterJobDetailView.as_view(),
        name="project-cases-filter-job-detail",
    ),
    path(
        "<uuid:project>/project-cases-filter-job/resubmit/<uuid:job>/",
        view=views.ProjectCasesFilterJobResubmitView.as_view(),
        name="project-cases-filter-job-resubmit",
    ),
    # Set last seen changelog version for user and redirect to changelog.
    # TODO: move to sodar-core?
    path("new-features/", view=views.NewFeaturesView.as_view(), name="new-features"),
    #: Detail views for site-wide maintenance jobs.
    path(
        "clear-expired-job/<uuid:job>/",
        view=views.ClearExpiredExportedFilesJobDetailView.as_view(),
        name="clear-expired-job-detail",
    ),
    path(
        "clear-inactive-variant-set-job/<uuid:job>/",
        view=views.ClearInactiveVariantSetsJobDetailView.as_view(),
        name="clear-inactive-variant-set-job",
    ),
    path(
        "clear-old-kiosk-cases-job/<uuid:job>/",
        view=views.ClearOldKioskCasesJobDetailView.as_view(),
        name="clear-old-kiosk-cases-job-detail",
    ),
    path(
        "refresh-small-variant-summaries-job/<uuid:job>/",
        view=views.RefreshSmallVariantSummaryJobDetailView.as_view(),
        name="refresh-small-variant-summaries-job-detail",
    ),
]

# Ajax API views
ajax_urlpatterns = [
    path(
        "ajax/project/qc/<uuid:project>/",
        view=views_ajax.CaseListQcStatsAjaxView.as_view(),
        name="ajax-project-qc",
    ),
    path(
        "ajax/case/retrieve/<uuid:case>/",
        view=views_ajax.CaseRetrieveAjaxView.as_view(),
        name="ajax-case-retrieve",
    ),
    path(
        "ajax/query-case/list/<uuid:case>/",
        view=views_ajax.SmallVariantQueryListAjaxView.as_view(),
        name="ajax-query-case-list",
    ),
    path(
        "ajax/query/list-create/<uuid:case>/",
        view=views_ajax.SmallVariantQueryListCreateAjaxView.as_view(),
        name="ajax-query-list-create",
    ),
    path(
        "ajax/query/retrieve-update-destroy/<uuid:smallvariantquery>/",
        view=views_ajax.SmallVariantQueryRetrieveUpdateDestroyAjaxView.as_view(),
        name="ajax-query-retrieve-update-destroy",
    ),
    path(
        "ajax/query-result-set/list/<uuid:smallvariantquery>/",
        view=views_ajax.SmallVariantQueryResultSetListAjaxView.as_view(),
        name="ajax-query-result-set-list",
    ),
    path(
        "ajax/query-result-set/retrieve/<uuid:smallvariantqueryresultset>/",
        view=views_ajax.SmallVariantQueryResultSetRetrieveAjaxView.as_view(),
        name="ajax-query-result-set-retrieve",
    ),
    path(
        "ajax/query-result-row/list/<uuid:smallvariantqueryresultset>/",
        view=views_ajax.SmallVariantQueryResultRowListAjaxView.as_view(),
        name="ajax-query-result-row-list",
    ),
    path(
        "ajax/query-result-row/retrieve/<uuid:smallvariantqueryresultrow>/",
        view=views_ajax.SmallVariantQueryResultRowRetrieveAjaxView.as_view(),
        name="ajax-query-result-row-retrieve",
    ),
    path(
        "ajax/query-case/query-settings-shortcut/<uuid:case>/",
        view=views_ajax.SmallVariantQuerySettingsShortcutAjaxView.as_view(),
        name="ajax-query-settings-shortcut",
    ),
    path(
        "ajax/query-case/download/generate/tsv/<uuid:smallvariantquery>/",
        view=views_ajax.SmallVariantQueryDownloadGenerateAjaxView.as_view(),
        name="ajax-query-case-download-generate-tsv",
    ),
    path(
        "ajax/query-case/download/generate/vcf/<uuid:smallvariantquery>/",
        view=views_ajax.SmallVariantQueryDownloadGenerateAjaxView.as_view(),
        name="ajax-query-case-download-generate-vcf",
    ),
    path(
        "ajax/query-case/download/generate/xlsx/<uuid:smallvariantquery>/",
        view=views_ajax.SmallVariantQueryDownloadGenerateAjaxView.as_view(),
        name="ajax-query-case-download-generate-xlsx",
    ),
    path(
        "ajax/query-case/download/serve/<uuid:exportfilebgjob>/",
        view=views_ajax.SmallVariantQueryDownloadServeAjaxView.as_view(),
        name="ajax-query-case-download-serve",
    ),
    path(
        "ajax/query-case/download/status/<uuid:exportfilebgjob>/",
        view=views_ajax.SmallVariantQueryDownloadStatusAjaxView.as_view(),
        name="ajax-query-case-download-status",
    ),
    path(
        "ajax/small-variant-comment/list-create/<uuid:case>/",
        view=views_ajax.SmallVariantCommentListCreateAjaxView.as_view(),
        name="ajax-small-variant-comment-list-create",
    ),
    path(
        "ajax/small-variant-comment/list-project/<uuid:project>/",
        view=views_ajax.SmallVariantCommentListProjectAjaxView.as_view(),
        name="ajax-small-variant-comment-list-project",
    ),
    path(
        "ajax/small-variant-comment/update/<uuid:smallvariantcomment>/",
        view=views_ajax.SmallVariantCommentUpdateAjaxView.as_view(),
        name="ajax-small-variant-comment-update",
    ),
    path(
        "ajax/small-variant-comment/delete/<uuid:smallvariantcomment>/",
        view=views_ajax.SmallVariantCommentDeleteAjaxView.as_view(),
        name="ajax-small-variant-comment-delete",
    ),
    path(
        "ajax/small-variant-flags/list-create/<uuid:case>/",
        view=views_ajax.SmallVariantFlagsListCreateAjaxView.as_view(),
        name="ajax-small-variant-flags-list-create",
    ),
    path(
        "ajax/small-variant-flags/list-project/<uuid:project>/",
        view=views_ajax.SmallVariantFlagsListProjectAjaxView.as_view(),
        name="ajax-small-variant-flags-list-project",
    ),
    path(
        "ajax/small-variant-flags/update/<uuid:smallvariantflags>/",
        view=views_ajax.SmallVariantFlagsUpdateAjaxView.as_view(),
        name="ajax-small-variant-flags-update",
    ),
    path(
        "ajax/small-variant-flags/delete/<uuid:smallvariantflags>/",
        view=views_ajax.SmallVariantFlagsDeleteAjaxView.as_view(),
        name="ajax-small-variant-flags-delete",
    ),
    path(
        "ajax/acmg-criteria-rating/list-create/<uuid:case>/",
        view=views_ajax.AcmgCriteriaRatingListCreateAjaxView.as_view(),
        name="ajax-acmg-criteria-rating-list-create",
    ),
    path(
        "ajax/acmg-criteria-rating/update/<uuid:acmgcriteriarating>/",
        view=views_ajax.AcmgCriteriaRatingUpdateAjaxView.as_view(),
        name="ajax-acmg-criteria-rating-update",
    ),
    path(
        "ajax/acmg-criteria-rating/delete/<uuid:acmgcriteriarating>/",
        view=views_ajax.AcmgCriteriaRatingDeleteAjaxView.as_view(),
        name="ajax-acmg-criteria-rating-delete",
    ),
    path(
        "ajax/extra-anno-fields/",
        view=views_ajax.ExtraAnnoFieldsApiView.as_view(),
        name="ajax-extra-anno-fields",
    ),
    path(
        "ajax/project-settings/retrieve/<uuid:project>/",
        view=views_ajax.ProjectSettingsRetrieveAjaxView.as_view(),
        name="ajax-project-settings-retrieve",
    ),
]

api_urlpatterns = [
    path(
        "api/project/qc/<uuid:project>/",
        view=views_api.CaseListQcStatsApiView.as_view(),
        name="api-project-qc",
    ),
    path(
        "api/case/retrieve/<uuid:case>/",
        view=views_api.CaseRetrieveApiView.as_view(),
        name="api-case-retrieve",
    ),
    path(
        "api/query-case/list/<uuid:case>/",
        view=views_api.SmallVariantQueryListApiView.as_view(),
        name="api-query-case-list",
    ),
    path(
        "api/query/list-create/<uuid:case>/",
        view=views_api.SmallVariantQueryListCreateApiView.as_view(),
        name="api-query-list-create",
    ),
    path(
        "api/query/retrieve-update-destroy/<uuid:smallvariantquery>/",
        view=views_api.SmallVariantQueryRetrieveUpdateDestroyApiView.as_view(),
        name="api-query-retrieve-update-destroy",
    ),
    path(
        "api/query-result-set/list/<uuid:smallvariantquery>/",
        view=views_api.SmallVariantQueryResultSetListApiView.as_view(),
        name="api-query-result-set-list",
    ),
    path(
        "api/query-result-set/retrieve/<uuid:smallvariantqueryresultset>/",
        view=views_api.SmallVariantQueryResultSetRetrieveApiView.as_view(),
        name="api-query-result-set-retrieve",
    ),
    path(
        "api/query-result-row/list/<uuid:smallvariantqueryresultset>/",
        view=views_api.SmallVariantQueryResultRowListApiView.as_view(),
        name="api-query-result-row-list",
    ),
    path(
        "api/query-result-row/retrieve/<uuid:smallvariantqueryresultrow>/",
        view=views_api.SmallVariantQueryResultRowRetrieveApiView.as_view(),
        name="api-query-result-row-retrieve",
    ),
    path(
        "api/query-case/query-settings-shortcut/<uuid:case>/",
        view=views_api.SmallVariantQuerySettingsShortcutApiView.as_view(),
        name="api-query-settings-shortcut",
    ),
    path(
        "api/query-case/quick-presets/",
        view=views_api.SmallVariantQuickPresetsApiView.as_view(),
        name="api-quick-presets",
    ),
    path(
        "api/query-case/category-presets/<str:category>/",
        view=views_api.SmallVariantCategoryPresetsApiView.as_view(),
        name="api-category-presets",
    ),
    path(
        "api/query-case/inheritance-presets/<uuid:case>/",
        view=views_api.SmallVariantInheritancePresetsApiView.as_view(),
        name="api-inheritance-presets",
    ),
    path(
        "api/query-case/download/generate/tsv/<uuid:smallvariantquery>/",
        view=views_api.SmallVariantQueryDownloadGenerateApiView.as_view(),
        name="api-query-case-download-generate-tsv",
    ),
    path(
        "api/query-case/download/generate/vcf/<uuid:smallvariantquery>/",
        view=views_api.SmallVariantQueryDownloadGenerateApiView.as_view(),
        name="api-query-case-download-generate-vcf",
    ),
    path(
        "api/query-case/download/generate/xlsx/<uuid:smallvariantquery>/",
        view=views_api.SmallVariantQueryDownloadGenerateApiView.as_view(),
        name="api-query-case-download-generate-xlsx",
    ),
    path(
        "api/query-case/download/serve/<uuid:exportfilebgjob>/",
        view=views_api.SmallVariantQueryDownloadServeApiView.as_view(),
        name="api-query-case-download-serve",
    ),
    path(
        "api/query-case/download/status/<uuid:exportfilebgjob>/",
        view=views_api.SmallVariantQueryDownloadStatusApiView.as_view(),
        name="api-query-case-download-status",
    ),
    path(
        "api/small-variant-comment/list-create/<uuid:case>/",
        view=views_api.SmallVariantCommentListCreateApiView.as_view(),
        name="api-small-variant-comment-list-create",
    ),
    path(
        "api/small-variant-comment/list-project/<uuid:project>/",
        view=views_api.SmallVariantCommentListProjectApiView.as_view(),
        name="api-small-variant-comment-list-project",
    ),
    path(
        "api/small-variant-comment/update/<uuid:smallvariantcomment>/",
        view=views_api.SmallVariantCommentUpdateApiView.as_view(),
        name="api-small-variant-comment-update",
    ),
    path(
        "api/small-variant-comment/delete/<uuid:smallvariantcomment>/",
        view=views_api.SmallVariantCommentDeleteApiView.as_view(),
        name="api-small-variant-comment-delete",
    ),
    path(
        "api/small-variant-flags/list-create/<uuid:case>/",
        view=views_api.SmallVariantFlagsListCreateApiView.as_view(),
        name="api-small-variant-flags-list-create",
    ),
    path(
        "api/small-variant-flags/list-project/<uuid:project>/",
        view=views_api.SmallVariantFlagsListProjectApiView.as_view(),
        name="api-small-variant-flags-list-project",
    ),
    path(
        "api/small-variant-flags/update/<uuid:smallvariantflags>/",
        view=views_api.SmallVariantFlagsUpdateApiView.as_view(),
        name="api-small-variant-flags-update",
    ),
    path(
        "api/small-variant-flags/delete/<uuid:smallvariantflags>/",
        view=views_api.SmallVariantFlagsDeleteApiView.as_view(),
        name="api-small-variant-flags-delete",
    ),
    path(
        "api/acmg-criteria-rating/list-create/<uuid:case>/",
        view=views_api.AcmgCriteriaRatingListCreateApiView.as_view(),
        name="api-acmg-criteria-rating-list-create",
    ),
    path(
        "api/acmg-criteria-rating/update/<uuid:acmgcriteriarating>/",
        view=views_api.AcmgCriteriaRatingUpdateApiView.as_view(),
        name="api-acmg-criteria-rating-update",
    ),
    path(
        "api/acmg-criteria-rating/delete/<uuid:acmgcriteriarating>/",
        view=views_api.AcmgCriteriaRatingDeleteApiView.as_view(),
        name="api-acmg-criteria-rating-delete",
    ),
    path(
        "api/extra-anno-fields/",
        view=views_api.ExtraAnnoFieldsApiView.as_view(),
        name="api-extra-anno-fields",
    ),
    path(
        "api/project-settings/retrieve/<uuid:project>/",
        view=views_api.ProjectSettingsRetrieveApiView.as_view(),
        name="api-project-settings-retrieve",
    ),
    path(
        "api/export-filter-settings/",
        view=views_api.export_filter_settings,
        name="api-export-filter-settings",
    ),
    path(
        "api/export-preset-settings/",
        view=views_api.export_preset_settings,
        name="api-export-preset-settings",
    ),
]


urlpatterns = (
    ui_urlpatterns
    + ajax_urlpatterns
    + annos_ajax_urlpatterns
    + presets_ajax_urlpatterns
    + api_urlpatterns
)
