# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-23 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import var_stats_qc.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReferenceSite",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("release", models.CharField(max_length=32)),
                ("chromosome", models.CharField(max_length=32)),
                ("position", models.IntegerField()),
                ("reference", models.CharField(max_length=1)),
                ("alternative", models.CharField(max_length=1)),
            ],
            managers=[("objects", var_stats_qc.models.CopyManagerInMigration())],
        ),
        migrations.AddIndex(
            model_name="referencesite",
            index=models.Index(
                fields=["release", "chromosome", "position"], name="var_stats_q_release_ab7606_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="referencesite",
            unique_together=set(
                [("release", "chromosome", "position", "reference", "alternative")]
            ),
        ),
    ]
