# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-19 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("var_stats_qc", "0002_import_grch37_sites")]

    operations = [
        migrations.RemoveIndex(model_name="referencesite", name="var_stats_q_release_ab7606_idx"),
        migrations.RenameField(model_name="referencesite", old_name="position", new_name="start"),
        migrations.AddField(
            model_name="referencesite",
            name="bin",
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="referencesite",
            name="end",
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="referencesite",
            unique_together=set([("release", "chromosome", "start", "reference", "alternative")]),
        ),
        migrations.AddIndex(
            model_name="referencesite",
            index=models.Index(
                fields=["release", "chromosome", "start"], name="var_stats_q_release_93b591_idx"
            ),
        ),
    ]
