# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-28 07:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("var_stats_qc", "0003_auto_20190619_1636")]

    operations = [
        migrations.RemoveField(model_name="referencesite", name="bin"),
        migrations.RemoveField(model_name="referencesite", name="end"),
    ]
