# Generated by Django 3.2.23 on 2024-02-20 14:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dbsnp", "0003_auto_20190705_1321"),
    ]

    operations = [
        migrations.RunSQL(
            r"""ALTER TABLE "dbsnp_dbsnp" ALTER COLUMN "id" TYPE bigint USING "id"::bigint""",
            r"""ALTER TABLE "dbsnp_dbsnp" ALTER COLUMN "id" TYPE integer USING "id"::integer""",
        ),
    ]
