# Generated by Django 3.2.20 on 2023-07-11 10:39

import uuid

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EnrichmentKit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "sodar_uuid",
                    models.UUIDField(
                        default=uuid.uuid4, help_text="Record SODAR UUID", unique=True
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, help_text="DateTime of creation"),
                ),
                (
                    "date_modified",
                    models.DateTimeField(auto_now=True, help_text="DateTime of last modification"),
                ),
                (
                    "identifier",
                    models.CharField(
                        help_text="Identifier of the enrichment kit, e.g., 'agilent-all-exon-v4'.",
                        max_length=128,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Identifier may only contain alphanumeric characters, hyphens, and underscores.",
                                regex="^[\\w_-]+$",
                            )
                        ],
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Title of the enrichment kit", max_length=128),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of the enrichment kit",
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ("identifier",),
            },
        ),
        migrations.CreateModel(
            name="TargetBedFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "sodar_uuid",
                    models.UUIDField(
                        default=uuid.uuid4, help_text="Record SODAR UUID", unique=True
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, help_text="DateTime of creation"),
                ),
                (
                    "date_modified",
                    models.DateTimeField(auto_now=True, help_text="DateTime of last modification"),
                ),
                ("file_uri", models.URLField(help_text="The file's URI.", max_length=512)),
                (
                    "genome_release",
                    models.CharField(
                        choices=[("grch37", "GRCh37"), ("grch38", "GRCh38")],
                        default="grch37",
                        help_text="The file's reference genome.",
                        max_length=16,
                    ),
                ),
                (
                    "enrichmentkit",
                    models.ForeignKey(
                        help_text="The enrichment kit that this file belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="seqmeta.enrichmentkit",
                    ),
                ),
            ],
            options={
                "ordering": ("genome_release", "file_uri"),
                "unique_together": {("enrichmentkit", "genome_release")},
            },
        ),
    ]
