# Generated by Django 3.2.20 on 2023-07-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seqmeta", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="targetbedfile",
            name="file_uri",
            field=models.CharField(help_text="The file's URI.", max_length=512),
        ),
    ]
