# Generated by Django 3.2.25 on 2024-07-01 05:39

import uuid

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import django_pydantic_field.compat.django
import django_pydantic_field.fields
import modelcluster.fields

import seqvars.models


class Migration(migrations.Migration):

    dependencies = [
        ("seqvars", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="querypresetsclinvar",
            name="presetssetversion",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE, to="seqvars.querypresetssetversion"
            ),
        ),
        migrations.AlterField(
            model_name="querypresetscolumns",
            name="presetssetversion",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE, to="seqvars.querypresetssetversion"
            ),
        ),
        migrations.AlterField(
            model_name="querypresetsconsequence",
            name="presetssetversion",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE, to="seqvars.querypresetssetversion"
            ),
        ),
        migrations.AlterField(
            model_name="querypresetsfrequency",
            name="presetssetversion",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE, to="seqvars.querypresetssetversion"
            ),
        ),
        migrations.AlterField(
            model_name="querypresetslocus",
            name="presetssetversion",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE, to="seqvars.querypresetssetversion"
            ),
        ),
        migrations.AlterField(
            model_name="querypresetsphenotypeprio",
            name="presetssetversion",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE, to="seqvars.querypresetssetversion"
            ),
        ),
        migrations.AlterField(
            model_name="querypresetsphenotypeprio",
            name="terms",
            field=django_pydantic_field.fields.PydanticSchemaField(
                config=None,
                default=list,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                schema=django_pydantic_field.compat.django.GenericContainer(
                    list, (seqvars.models.TermPresence,)
                ),
            ),
        ),
        migrations.AlterField(
            model_name="querypresetsquality",
            name="presetssetversion",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE, to="seqvars.querypresetssetversion"
            ),
        ),
        migrations.AlterField(
            model_name="querypresetssetversion",
            name="presetsset",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="seqvars.querypresetsset",
            ),
        ),
        migrations.AlterField(
            model_name="querypresetsvariantprio",
            name="presetssetversion",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE, to="seqvars.querypresetssetversion"
            ),
        ),
        migrations.AlterField(
            model_name="querysettingsphenotypeprio",
            name="terms",
            field=django_pydantic_field.fields.PydanticSchemaField(
                config=None,
                default=list,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                schema=django_pydantic_field.compat.django.GenericContainer(
                    list, (seqvars.models.TermPresence,)
                ),
            ),
        ),
        migrations.CreateModel(
            name="PredefinedQuery",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sodar_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("rank", models.IntegerField()),
                ("label", models.CharField(max_length=128)),
                ("description", models.TextField(null=True)),
                ("included_in_sop", models.BooleanField(default=False)),
                (
                    "clinvar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="seqvars.querypresetsclinvar",
                    ),
                ),
                (
                    "columns",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="seqvars.querypresetscolumns",
                    ),
                ),
                (
                    "consequence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="seqvars.querypresetsconsequence",
                    ),
                ),
                (
                    "frequency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="seqvars.querypresetsfrequency",
                    ),
                ),
                (
                    "locus",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="seqvars.querypresetslocus",
                    ),
                ),
                (
                    "phenotypeprio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="seqvars.querypresetsphenotypeprio",
                    ),
                ),
                (
                    "presetssetversion",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="seqvars.querypresetssetversion",
                    ),
                ),
                (
                    "quality",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="seqvars.querypresetsquality",
                    ),
                ),
                (
                    "variantprio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="seqvars.querypresetsvariantprio",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
