# Generated by Django 3.2.25 on 2024-06-26 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("seqvars", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seqvarquerysettingsfrequency",
            name="querysettings",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="seqvars.seqvarquerysettings"
            ),
        ),
    ]
