# Generated by Django 3.2.25 on 2024-06-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seqvars", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="querypresetsclinvar",
            name="allow_conflicting_interpretations",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="querysettingsclinvar",
            name="allow_conflicting_interpretations",
            field=models.BooleanField(default=False),
        ),
    ]
