# Generated by Django 3.2.25 on 2024-06-28 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("seqvars", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="querypresetssetversion",
            name="signed_off_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
