# Generated by Django 3.2.25 on 2024-06-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seqvars", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="seqvarpresetsfrequency",
            old_name="helixmtdb_het_count",
            new_name="helixmtdb_heteroplasmic",
        ),
        migrations.RenameField(
            model_name="seqvarpresetsfrequency",
            old_name="helixmtdb_hom_count",
            new_name="helixmtdb_homoplasmic",
        ),
        migrations.RenameField(
            model_name="seqvarquerysettingsfrequency",
            old_name="helixmtdb_het_count",
            new_name="helixmtdb_heteroplasmic",
        ),
        migrations.RenameField(
            model_name="seqvarquerysettingsfrequency",
            old_name="helixmtdb_hom_count",
            new_name="helixmtdb_homoplasmic",
        ),
        migrations.AddField(
            model_name="seqvarpresetsfrequency",
            name="gnomad_exomes_frequency",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="seqvarquerysettingsfrequency",
            name="gnomad_exomes_frequency",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
