# Generated by Django 3.2.25 on 2024-06-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seqvars", "0002_alter_query_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="querypresetsconsequence",
            name="max_distance_to_exon",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="querysettingsconsequence",
            name="max_distance_to_exon",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
