# Generated by Django 3.2.25 on 2024-07-01 09:55

import typing

import django.core.serializers.json
from django.db import migrations
import django_pydantic_field.compat.django
import django_pydantic_field.fields

import seqvars.models


class Migration(migrations.Migration):

    dependencies = [
        ("seqvars", "0002_auto_20240701_0539"),
    ]

    operations = [
        migrations.AddField(
            model_name="querypresetsset",
            name="genotype",
            field=django_pydantic_field.fields.PydanticSchemaField(
                config=None,
                default=None,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                schema=django_pydantic_field.compat.django.GenericContainer(
                    typing.Union, (seqvars.models.GenotypePresets, type(None))
                ),
            ),
        ),
    ]
