# Generated by Django 3.2.25 on 2024-06-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seqvars", "0003_auto_20240628_1240"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="querypresetsquality",
            name="on_failure",
        ),
        migrations.AddField(
            model_name="querypresetsquality",
            name="filter_active",
            field=models.BooleanField(default=False),
        ),
    ]
