# Generated by Django 3.2.25 on 2024-08-07 10:06

import typing

import django.core.serializers.json
from django.db import migrations
import django_pydantic_field.compat.django
import django_pydantic_field.fields

import seqvars.models.base


class Migration(migrations.Migration):

    dependencies = [
        ("seqvars", "0005_seqvarsquerysettingsgenotype_recessive_mode"),
    ]

    operations = [
        migrations.RenameField(
            model_name="seqvarsresultrow",
            old_name="alternative",
            new_name="alt_allele",
        ),
        migrations.RenameField(
            model_name="seqvarsresultrow",
            old_name="chromosome",
            new_name="chrom",
        ),
        migrations.RenameField(
            model_name="seqvarsresultrow",
            old_name="chromosome_no",
            new_name="chrom_no",
        ),
        migrations.RenameField(
            model_name="seqvarsresultrow",
            old_name="release",
            new_name="genome_release",
        ),
        migrations.RenameField(
            model_name="seqvarsresultrow",
            old_name="start",
            new_name="pos",
        ),
        migrations.RenameField(
            model_name="seqvarsresultrow",
            old_name="reference",
            new_name="ref_allele",
        ),
        migrations.RemoveField(
            model_name="seqvarsresultrow",
            name="stop",
        ),
        migrations.AddField(
            model_name="seqvarsresultset",
            name="output_header",
            field=django_pydantic_field.fields.PydanticSchemaField(
                config=None,
                default=None,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
                schema=django_pydantic_field.compat.django.GenericContainer(
                    typing.Union, (seqvars.models.base.SeqvarsOutputHeaderPydantic, type(None))
                ),
            ),
        ),
        migrations.AlterField(
            model_name="seqvarsresultrow",
            name="payload",
            field=django_pydantic_field.fields.PydanticSchemaField(
                config=None,
                default=None,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
                schema=django_pydantic_field.compat.django.GenericContainer(
                    typing.Union, (seqvars.models.base.SeqvarsOutputRecordPydantic, type(None))
                ),
            ),
        ),
        migrations.AlterField(
            model_name="seqvarsresultset",
            name="datasource_infos",
            field=django_pydantic_field.fields.PydanticSchemaField(
                config=None,
                default=None,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
                schema=django_pydantic_field.compat.django.GenericContainer(
                    typing.Union, (seqvars.models.base.DataSourceInfosPydantic, type(None))
                ),
            ),
        ),
    ]
