# Generated by Django 3.2.25 on 2024-09-03 06:29

import uuid

import bgjobs.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projectroles", "0028_populate_finder_role"),
        ("bgjobs", "0006_auto_20200526_1657"),
        ("seqvars", "0007_auto_20240822_1314"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeqvarsQueryExecutionBackgroundJob",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sodar_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "bg_job",
                    models.ForeignKey(
                        help_text="Background job for state etc.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seqvarsqueryexecutionbackgroundjob",
                        to="bgjobs.backgroundjob",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="projectroles.project"
                    ),
                ),
                (
                    "seqvarsqueryexecution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="seqvars.seqvarsqueryexecution",
                    ),
                ),
            ],
            bases=(bgjobs.models.JobModelMessageMixin, models.Model),
        ),
    ]
