# Generated by Django 3.2.25 on 2024-09-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seqvars", "0008_seqvarsqueryexecutionbackgroundjob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seqvarsresultrow",
            name="genome_release",
            field=models.CharField(
                choices=[("grch37", "GRCh37"), ("grch38", "GRCh38")], max_length=32
            ),
        ),
    ]
