# Generated by Django 3.2.25 on 2024-09-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seqvars", "0009_alter_seqvarsresultrow_genome_release"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="seqvarsqueryexecutionbackgroundjob",
            options={"ordering": ["-pk"]},
        ),
        migrations.AlterModelOptions(
            name="seqvarsresultrow",
            options={"ordering": ["chrom_no", "pos", "ref_allele", "alt_allele"]},
        ),
        migrations.AlterModelOptions(
            name="seqvarsresultset",
            options={"ordering": ["-date_created"]},
        ),
        migrations.AlterField(
            model_name="seqvarsresultrow",
            name="genome_release",
            field=models.CharField(
                choices=[("grch37", "GRCh37"), ("grch38", "GRCh38")], max_length=32
            ),
        ),
    ]
