# Generated by Django 3.2.25 on 2024-10-21 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seqvars", "0010_auto_20240905_1017"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="seqvarsqueryexecution",
            options={"ordering": ["-date_created"]},
        ),
    ]
