# Generated by Django 3.2.25 on 2024-10-24 08:23

import uuid

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import django_pydantic_field.compat.django
import django_pydantic_field.fields
import model_clone.mixin

import seqvars.models.base


class Migration(migrations.Migration):

    dependencies = [
        ("seqvars", "0011_alter_seqvarsqueryexecution_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeqvarsQuerySettingsColumns",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sodar_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "column_settings",
                    django_pydantic_field.fields.PydanticSchemaField(
                        config=None,
                        default=list,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        schema=django_pydantic_field.compat.django.GenericContainer(
                            list, (seqvars.models.base.SeqvarsColumnConfigPydantic,)
                        ),
                    ),
                ),
                (
                    "querysettings",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="columns",
                        to="seqvars.seqvarsquerysettings",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name="seqvarsquery",
            name="columnsconfig",
        ),
        migrations.DeleteModel(
            name="SeqvarsQueryColumnsConfig",
        ),
    ]
