# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-03 17:09
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [("svs", "0005_importstructuralvariantbgjob")]

    operations = [
        migrations.AlterModelOptions(
            name="structuralvariant", options={"managed": settings.IS_TESTING}
        ),
        migrations.AlterModelOptions(
            name="structuralvariantgeneannotation", options={"managed": settings.IS_TESTING}
        ),
    ]
