# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-03 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("svs", "0005_importstructuralvariantbgjob")]

    operations = [
        migrations.AlterModelOptions(name="structuralvariant", options={"managed": False}),
        migrations.AlterModelOptions(
            name="structuralvariantgeneannotation", options={"managed": False}
        ),
    ]
