# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-09 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("variants", "0078_exportprojectcasesfilebgjob_cohort"),
        ("svs", "0012_structuralvariantflags_flag_molecular"),
    ]

    operations = [
        migrations.CreateModel(
            name="SvAnnotationReleaseInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("genomebuild", models.CharField(default="GRCh37", max_length=32)),
                ("table", models.CharField(max_length=512)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("release", models.CharField(max_length=512)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="variants.Case"
                    ),
                ),
                (
                    "variant_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="svs.StructuralVariantSet"
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="svannotationreleaseinfo",
            unique_together=set([("genomebuild", "table", "variant_set")]),
        ),
    ]
