# Generated by Django 3.2.7 on 2021-10-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("svs", "0015_set_logged_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="structuralvariantset",
            name="release",
            field=models.CharField(default="GRCh37", max_length=32, null=True),
        ),
    ]
