# Generated by Django 3.2.12 on 2022-06-27 13:40

import bgjobs.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("bgjobs", "0006_auto_20200526_1657"),
        ("svs", "0016_structuralvariantset_release"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackgroundSvSet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "sodar_uuid",
                    models.UUIDField(
                        default=uuid.uuid4, help_text="Record SODAR UUID", unique=True
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, help_text="DateTime of creation"),
                ),
                (
                    "date_modified",
                    models.DateTimeField(auto_now=True, help_text="DateTime of last modification"),
                ),
                ("genomebuild", models.CharField(default="GRCh37", max_length=32)),
                (
                    "varfish_version",
                    models.CharField(
                        blank=True,
                        help_text="Version of varfish server used to build the set",
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("initial", "initial"),
                            ("building", "build in progress"),
                            ("ready", "ready but not active"),
                            ("active", "active"),
                            ("inactive", "inactive"),
                            ("deleting", "deletion in progress"),
                        ],
                        default="initial",
                        max_length=32,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CleanupBackgroundSvSetJob",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, help_text="DateTime of creation"),
                ),
                (
                    "sodar_uuid",
                    models.UUIDField(default=uuid.uuid4, help_text="Case SODAR UUID", unique=True),
                ),
                (
                    "bg_job",
                    models.ForeignKey(
                        help_text="Background job for state etc.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="svs_cleanupbackgroundsvsetjob_related",
                        to="bgjobs.backgroundjob",
                    ),
                ),
            ],
            options={"ordering": ("-date_created",), "abstract": False,},
            bases=(bgjobs.models.JobModelMessageMixin, models.Model),
        ),
        migrations.CreateModel(
            name="BuildBackgroundSvSetJob",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, help_text="DateTime of creation"),
                ),
                (
                    "sodar_uuid",
                    models.UUIDField(default=uuid.uuid4, help_text="Case SODAR UUID", unique=True),
                ),
                ("genomebuild", models.CharField(default="GRCh37", max_length=32)),
                (
                    "bg_job",
                    models.ForeignKey(
                        help_text="Background job for state etc.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="svs_buildbackgroundsvsetjob_related",
                        to="bgjobs.backgroundjob",
                    ),
                ),
            ],
            options={"ordering": ("-date_created",), "abstract": False,},
            bases=(bgjobs.models.JobModelMessageMixin, models.Model),
        ),
        migrations.CreateModel(
            name="BackgroundSv",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("release", models.CharField(max_length=32)),
                ("chromosome", models.CharField(max_length=32)),
                ("chromosome_no", models.IntegerField()),
                ("start", models.IntegerField()),
                ("chromosome2", models.CharField(max_length=32)),
                ("chromosome_no2", models.IntegerField()),
                ("end", models.IntegerField()),
                (
                    "pe_orientation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("3to3", "3to3"),
                            ("3to5", "3to5"),
                            ("5to3", "5to3"),
                            ("5to5", "5to5"),
                        ],
                        max_length=4,
                        null=True,
                    ),
                ),
                (
                    "sv_type",
                    models.CharField(
                        choices=[
                            ("DEL", "deletion"),
                            ("DUP", "duplication"),
                            ("INS", "insertion"),
                            ("INV", "inversion"),
                            ("BND", "breakend"),
                            ("CNV", "copy number variation"),
                        ],
                        max_length=32,
                    ),
                ),
                ("bin", models.IntegerField()),
                ("src_count", models.IntegerField()),
                ("carriers", models.IntegerField()),
                ("carriers_het", models.IntegerField()),
                ("carriers_hom", models.IntegerField()),
                ("carriers_hemi", models.IntegerField()),
                (
                    "bg_sv_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="svs.backgroundsvset"
                    ),
                ),
            ],
        ),
    ]
