# Generated by Django 3.2.23 on 2024-02-08 16:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("svs", "0022_auto_20230801_1417"),
    ]

    operations = [
        migrations.RunSQL(
            r"""ALTER TABLE "svs_svqueryresultrow" ALTER COLUMN "id" TYPE bigint USING "id"::bigint""",
            r"""ALTER TABLE "svs_svqueryresultrow" ALTER COLUMN "id" TYPE integer USING "id"::integer""",
        ),
        migrations.RunSQL(
            r"""ALTER TABLE "svs_svqueryresultset" ALTER COLUMN "id" TYPE bigint USING "id"::bigint""",
            r"""ALTER TABLE "svs_svqueryresultset" ALTER COLUMN "id" TYPE integer USING "id"::integer""",
        ),
    ]
