# Generated by Django 3.2.24 on 2024-03-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("svs", "0024_clear_sv_queries"),
    ]

    operations = [
        migrations.AddField(
            model_name="structuralvariantflags",
            name="flag_incidental",
            field=models.BooleanField(default=False),
        ),
    ]
