# Generated by Django 3.2.25 on 2024-05-22 13:53

import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("variants", "0104_remove_hgmd_dbsnp_filter_from_query_settings"),
        ("svs", "0025_structuralvariantflags_flag_incidental"),
    ]

    operations = [
        migrations.CreateModel(
            name="StructuralVariantAcmgRating",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "sodar_uuid",
                    models.UUIDField(default=uuid.uuid4, help_text="Annotation UUID", unique=True),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, help_text="DateTime of creation"),
                ),
                (
                    "date_modified",
                    models.DateTimeField(auto_now=True, help_text="DateTime of last modification"),
                ),
                ("bin", models.IntegerField()),
                ("release", models.CharField(max_length=32)),
                ("chromosome", models.CharField(max_length=32)),
                ("start", models.IntegerField()),
                ("end", models.IntegerField()),
                ("sv_type", models.CharField(max_length=32)),
                ("sv_sub_type", models.CharField(max_length=32)),
                (
                    "class_override",
                    models.FloatField(
                        blank=True,
                        default=None,
                        help_text="Use this field to override the auto-computed class assignment",
                        null=True,
                        verbose_name="Class Override",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        help_text="Case that this SV is rated in",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="structural_variant_acmg_ratings",
                        to="variants.case",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="structuralvariantacmgrating",
            index=models.Index(
                fields=["case", "release", "bin"], name="svs_structu_case_id_943501_idx"
            ),
        ),
    ]
