# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-05 07:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20181015_1316"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["name", "username"]},
        ),
    ]
