# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-31 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0003_auto_20181031_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='DateTime of creation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, help_text='DateTime of last modification'),
        ),
    ]
