# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-13 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [("variants", "0007_auto_20181108_1122")]

    operations = [
        migrations.CreateModel(
            name="SmallVariantFlags",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, help_text="DateTime of creation"),
                ),
                (
                    "date_modified",
                    models.DateTimeField(auto_now=True, help_text="DateTime of last modification"),
                ),
                (
                    "sodar_uuid",
                    models.UUIDField(
                        default=uuid.uuid4, help_text="Small variant flags SODAR UUID", unique=True
                    ),
                ),
                ("release", models.CharField(max_length=32)),
                ("chromosome", models.CharField(max_length=32)),
                ("position", models.IntegerField()),
                ("reference", models.CharField(max_length=512)),
                ("alternative", models.CharField(max_length=512)),
                ("flag_bookmarked", models.BooleanField(default=False)),
                ("flag_candidate", models.BooleanField(default=False)),
                ("flag_final_causative", models.BooleanField(default=False)),
                ("flag_for_validation", models.BooleanField(default=False)),
                (
                    "flag_visual",
                    models.CharField(
                        choices=[
                            ("positive", "positive"),
                            ("uncertain", "uncertain"),
                            ("negative", "negative"),
                            ("empty", "empty"),
                        ],
                        default="empty",
                        max_length=32,
                    ),
                ),
                (
                    "flag_validation",
                    models.CharField(
                        choices=[
                            ("positive", "positive"),
                            ("uncertain", "uncertain"),
                            ("negative", "negative"),
                            ("empty", "empty"),
                        ],
                        default="empty",
                        max_length=32,
                    ),
                ),
                (
                    "flag_phenotype_match",
                    models.CharField(
                        choices=[
                            ("positive", "positive"),
                            ("uncertain", "uncertain"),
                            ("negative", "negative"),
                            ("empty", "empty"),
                        ],
                        default="empty",
                        max_length=32,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        help_text="Case that this variant is flagged in",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="small_variant_flags",
                        to="variants.Case",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="smallvariantflags",
            index=models.Index(
                fields=["release", "chromosome", "position", "reference", "alternative"],
                name="variants_sm_release_82b900_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="smallvariantflags",
            unique_together=set(
                [("release", "chromosome", "position", "reference", "alternative", "case")]
            ),
        ),
    ]
