# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-14 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("variants", "0012_auto_20181114_1914")]

    operations = [
        migrations.AddField(
            model_name="smallvariantflags",
            name="flag_summary",
            field=models.CharField(
                choices=[
                    ("positive", "positive"),
                    ("uncertain", "uncertain"),
                    ("negative", "negative"),
                    ("empty", "empty"),
                ],
                default="empty",
                max_length=32,
            ),
        )
    ]
