# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-15 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("variants", "0013_smallvariantflags_flag_summary")]

    operations = [
        migrations.RemoveIndex(model_name="smallvariant", name="variants_sm_exac_fr_f91f1b_idx"),
        migrations.RemoveIndex(model_name="smallvariant", name="variants_sm_exac_fr_b0171c_idx"),
        migrations.RemoveIndex(model_name="smallvariant", name="variants_sm_release_7dfe83_idx"),
        migrations.RemoveIndex(model_name="smallvariant", name="variants_sm_release_a0d99d_idx"),
        migrations.RemoveIndex(model_name="smallvariant", name="variants_sm_release_d3c4f3_idx"),
        migrations.RemoveIndex(model_name="smallvariant", name="variants_sm_ensembl_97f665_idx"),
        migrations.RemoveIndex(model_name="smallvariant", name="variants_sm_refseq__54639f_idx"),
    ]
