# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-16 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("variants", "0014_auto_20181115_1426")]

    operations = [
        migrations.AddIndex(
            model_name="smallvariantcomment",
            index=models.Index(
                fields=[
                    "release",
                    "chromosome",
                    "position",
                    "reference",
                    "alternative",
                    "case",
                    "ensembl_gene_id",
                ],
                name="variants_sm_release_40b8cc_idx",
            ),
        )
    ]
