# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-19 11:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("variants", "0015_auto_20181116_1437"),
    ]

    operations = [
        migrations.CreateModel(
            name="SmallVariantQuery",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, help_text="DateTime of creation"),
                ),
                (
                    "sodar_uuid",
                    models.UUIDField(
                        default=uuid.uuid4, help_text="Small variant flags SODAR UUID", unique=True
                    ),
                ),
                ("form_id", models.CharField(help_text="Identifier of the form", max_length=100)),
                ("form_version", models.IntegerField(help_text="Version of form when saving")),
                ("query_settings", models.JSONField(help_text="The query settings"),),
                (
                    "name",
                    models.CharField(
                        default=None,
                        help_text="Optional user-assigned name",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "public",
                    models.BooleanField(
                        default=False, help_text="Case is flagged as public or not"
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        help_text="The case that the query relates to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="small_variant_queries",
                        to="variants.Case",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the query",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="small_variant_queries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        )
    ]
