# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-22 11:10
from __future__ import unicode_literals

import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projectroles", "0006_add_remote_projects"),
        ("bgjobs", "0004_backgroundjob_user"),
        ("variants", "0016_smallvariantquery"),
    ]

    operations = [
        migrations.CreateModel(
            name="DistillerSubmissionBgJob",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "sodar_uuid",
                    models.UUIDField(default=uuid.uuid4, help_text="Case SODAR UUID", unique=True),
                ),
                (
                    "query_args",
                    models.JSONField(help_text="(Validated) query parameters"),
                ),
                (
                    "distiller_project_id",
                    models.CharField(
                        help_text="The project ID that MutationDistiller assigned on submission",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "bg_job",
                    models.ForeignKey(
                        help_text="Background job for state etc.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distiller_submission_bg_job",
                        to="bgjobs.BackgroundJob",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        help_text="The case to export",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="variants.Case",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project in which this objects belongs",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projectroles.Project",
                    ),
                ),
            ],
        )
    ]
