# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-30 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("variants", "0023_auto_20181127_1315")]

    operations = [
        migrations.AlterUniqueTogether(name="smallvariantcomment", unique_together=set([]))
    ]
