# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-19 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("variants", "0027_filter_jobs_bigint_id_field")]

    operations = [
        migrations.CreateModel(
            name="AnnotationReleaseInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("genomebuild", models.CharField(default="GRCh37", max_length=32)),
                ("table", models.CharField(max_length=16)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("release", models.CharField(max_length=512)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="variants.Case"
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="annotationreleaseinfo",
            unique_together=set([("genomebuild", "table", "release", "case")]),
        ),
    ]
