# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-03 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("variants", "0034_smallvariantqueryvariantscores")]

    operations = [
        migrations.AlterField(
            model_name="annotationreleaseinfo", name="table", field=models.CharField(max_length=512)
        )
    ]
