# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-15 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("variants", "0036_auto_20190412_1113")]

    operations = [
        migrations.AlterUniqueTogether(
            name="annotationreleaseinfo", unique_together=set([("genomebuild", "table", "case")])
        )
    ]
