# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-07 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("variants", "0037_auto_20190415_0921")]

    operations = [migrations.AlterUniqueTogether(name="smallvariant", unique_together=set([]))]
