# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-28 12:33
from __future__ import unicode_literals

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("variants", "0044_adjust_smallvariantstats")]

    operations = [
        migrations.CreateModel(
            name="SmallVariantSet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, help_text="DateTime of creation"),
                ),
                (
                    "date_modified",
                    models.DateTimeField(auto_now=True, help_text="DateTime of last modification"),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("importing", "importing"),
                            ("active", "active"),
                            ("deleting", "deleting"),
                        ],
                        max_length=16,
                    ),
                ),
            ],
        ),
        migrations.RemoveIndex(model_name="smallvariant", name="variants_sm_case_id_6f9d8c_idx"),
        migrations.RemoveIndex(model_name="smallvariant", name="variants_sm_case_id_a529e8_gin"),
        migrations.RemoveIndex(model_name="smallvariant", name="variants_sm_case_id_071d6b_gin"),
        migrations.RemoveIndex(model_name="smallvariant", name="variants_sm_case_id_423a80_idx"),
        migrations.RemoveIndex(model_name="smallvariant", name="variants_sm_case_id_5d52f6_idx"),
        migrations.RemoveIndex(model_name="smallvariant", name="variants_sm_case_id_1f4f31_idx"),
        migrations.RemoveIndex(model_name="smallvariant", name="variants_sm_case_id_3efbb1_idx"),
        migrations.RenameField(model_name="smallvariant", old_name="case_id", new_name="set_id"),
        migrations.AddIndex(
            model_name="smallvariant",
            index=models.Index(fields=["set_id"], name="variants_sm_set_id_6512c1_idx"),
        ),
        migrations.AddIndex(
            model_name="smallvariant",
            index=models.Index(
                fields=["set_id", "chromosome", "bin"], name="variants_sm_set_id_b38281_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="smallvariant",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["set_id", "refseq_effect"], name="variants_sm_set_id_bc625e_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="smallvariant",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["set_id", "ensembl_effect"], name="variants_sm_set_id_60a43c_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="smallvariant",
            index=models.Index(
                fields=["set_id", "in_clinvar"], name="variants_sm_set_id_795351_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="smallvariant",
            index=models.Index(
                fields=["set_id", "ensembl_gene_id"], name="variants_sm_set_id_5407f7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="smallvariant",
            index=models.Index(
                fields=["set_id", "refseq_gene_id"], name="variants_sm_set_id_ada119_idx"
            ),
        ),
        migrations.AddField(
            model_name="smallvariantset",
            name="case",
            field=models.ForeignKey(
                help_text="The case that this set is for",
                on_delete=django.db.models.deletion.CASCADE,
                to="variants.Case",
            ),
        ),
    ]
