# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-28 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("variants", "0044_adjust_smallvariantstats")]

    operations = [
        migrations.AlterField(
            model_name="smallvariant",
            name="ensembl_transcript_id",
            field=models.CharField(max_length=32, null=True),
        )
    ]
