# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-01 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("variants", "0046_partition_smallvariants_table")]

    operations = [
        migrations.RemoveField(model_name="casevariantstats", name="case"),
        migrations.AddField(
            model_name="casevariantstats",
            name="variant_set",
            field=models.OneToOneField(
                default=-1,
                help_text="The variant statistics object for this variant set",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variant_stats",
                to="variants.SmallVariantSet",
            ),
            preserve_default=False,
        ),
    ]
