# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-03 11:59
from __future__ import unicode_literals

import uuid

import bgjobs.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bgjobs", "0005_auto_20190128_1210"),
        ("projectroles", "0010_update_appsetting"),
        ("variants", "0047_auto_20190701_1625"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportVariantsBgJob",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, help_text="DateTime of creation"),
                ),
                (
                    "sodar_uuid",
                    models.UUIDField(default=uuid.uuid4, help_text="Job UUID", unique=True),
                ),
                ("case_name", models.CharField(help_text="The case name", max_length=128)),
                ("index_name", models.CharField(help_text="The index name", max_length=128)),
                ("path_ped", models.CharField(help_text="Path to PED file", max_length=4096)),
                (
                    "path_genotypes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            help_text="Path to variants TSV file", max_length=4096
                        ),
                        size=None,
                    ),
                ),
                (
                    "path_db_info",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            help_text="Path to db-info TSV file", max_length=4096
                        ),
                        size=None,
                    ),
                ),
                (
                    "bg_job",
                    models.ForeignKey(
                        help_text="Background job for state etc.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants_importvariantsbgjob_related",
                        to="bgjobs.BackgroundJob",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project that is imported to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projectroles.Project",
                    ),
                ),
            ],
            bases=(bgjobs.models.JobModelMessageMixin, models.Model),
        )
    ]
