# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-03 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("variants", "0048_importvariantsbgjob")]

    operations = [
        migrations.AddField(
            model_name="annotationreleaseinfo",
            name="variant_set",
            field=models.ForeignKey(
                default=-1,
                on_delete=django.db.models.deletion.CASCADE,
                to="variants.SmallVariantSet",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="annotationreleaseinfo",
            unique_together=set([("genomebuild", "table", "variant_set")]),
        ),
    ]
