# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-08 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("variants", "0051_case_notes")]

    operations = [
        migrations.AddField(
            model_name="case",
            name="status",
            field=models.CharField(
                choices=[
                    ("initial", "initial"),
                    ("active", "active"),
                    ("closed-unsolved", "closed as unsolved"),
                    ("closed-solved", "closed as solved"),
                ],
                default=("initial", "initial"),
                max_length=32,
            ),
        )
    ]
