# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-09 16:36
from __future__ import unicode_literals

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("variants", "0052_case_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseComments",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "sodar_uuid",
                    models.UUIDField(default=uuid.uuid4, help_text="Case SODAR UUID", unique=True),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, help_text="DateTime of creation"),
                ),
                (
                    "date_modified",
                    models.DateTimeField(auto_now=True, help_text="DateTime of last modification"),
                ),
                ("comment", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="case",
            name="notes",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="case",
            name="status",
            field=models.CharField(
                choices=[
                    ("initial", "initial"),
                    ("active", "active"),
                    ("closed-unsolved", "closed as unsolved"),
                    ("closed-solved", "closed as solved"),
                ],
                default="initial",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="casecomments",
            name="case",
            field=models.ForeignKey(
                help_text="Case for this comment",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="case_comments",
                to="variants.Case",
            ),
        ),
        migrations.AddField(
            model_name="casecomments",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the comment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="case_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
