# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-17 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("variants", "0060_auto_20191004_1414")]

    operations = [
        migrations.AlterModelOptions(
            name="smallvariantcomment", options={"ordering": ["chromosome", "start", "end"]}
        ),
        migrations.AlterModelOptions(
            name="smallvariantflags", options={"ordering": ["chromosome", "start", "end"]}
        ),
        migrations.AddField(
            model_name="smallvariantflags",
            name="flag_doesnt_segregate",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="smallvariantflags",
            name="flag_no_disease_association",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="smallvariantflags",
            name="flag_segregates",
            field=models.BooleanField(default=False),
        ),
    ]
