# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-18 09:06
from __future__ import unicode_literals

from django.db import migrations, models

from variants.models import SmallVariantFlags, SmallVariantComment


def update_chromosome_no_in_existing_flags_and_comments(apps, schema_editor):
    if not schema_editor.connection.alias == "default":
        return
    for o in list(SmallVariantFlags.objects.all()) + list(SmallVariantComment.objects.all()):
        o.save()


class Migration(migrations.Migration):

    dependencies = [("variants", "0061_auto_20191017_0729")]

    operations = [
        migrations.AlterModelOptions(
            name="smallvariantcomment", options={"ordering": ["chromosome_no", "start", "end"]}
        ),
        migrations.AlterModelOptions(
            name="smallvariantflags", options={"ordering": ["chromosome_no", "start", "end"]}
        ),
        migrations.AddField(
            model_name="smallvariantcomment",
            name="chromosome_no",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="smallvariantflags",
            name="chromosome_no",
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(update_chromosome_no_in_existing_flags_and_comments),
    ]
