# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-22 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("variants", "0062_auto_20191018_0906")]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="status",
            field=models.CharField(
                choices=[
                    ("initial", "initial"),
                    ("active", "active"),
                    ("closed-unsolved", "closed as unsolved"),
                    ("closed-uncertain", "closed as uncertain"),
                    ("closed-solved", "closed as solved"),
                ],
                default="initial",
                max_length=32,
            ),
        )
    ]
