# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-25 14:03
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("variants", "0063_auto_20191022_1232")]

    operations = [
        migrations.CreateModel(
            name="CaddPathogenicityScoreCache",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "last_retrieved",
                    models.DateTimeField(auto_now=True, help_text="DateTime of last modification"),
                ),
                ("release", models.CharField(max_length=32)),
                ("chromosome", models.CharField(max_length=32)),
                ("start", models.IntegerField()),
                ("end", models.IntegerField()),
                ("bin", models.IntegerField()),
                ("reference", models.CharField(max_length=512)),
                ("alternative", models.CharField(max_length=512)),
                ("info", django.contrib.postgres.fields.jsonb.JSONField()),
                (
                    "scores",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), size=2
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="MutationTasterPathogenicityScoreCache",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "last_retrieved",
                    models.DateTimeField(auto_now=True, help_text="DateTime of last modification"),
                ),
                ("release", models.CharField(max_length=32)),
                ("chromosome", models.CharField(max_length=32)),
                ("start", models.IntegerField()),
                ("end", models.IntegerField()),
                ("bin", models.IntegerField()),
                ("reference", models.CharField(max_length=512)),
                ("alternative", models.CharField(max_length=512)),
                ("transcript_stable", models.CharField(max_length=32, null=True)),
                ("ncbi_geneid", models.CharField(max_length=16, null=True)),
                ("prediction", models.CharField(max_length=32, null=True)),
                ("model", models.CharField(max_length=32, null=True)),
                ("bayes_prob_dc", models.IntegerField(null=True)),
                ("note", models.CharField(max_length=512, null=True)),
                ("splicesite", models.CharField(max_length=32, null=True)),
                ("distance_from_splicesite", models.IntegerField(null=True)),
                ("disease_mutation", models.CharField(max_length=32, null=True)),
                ("polymorphism", models.CharField(max_length=32, null=True)),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="UmdPathogenicityScoreCache",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "last_retrieved",
                    models.DateTimeField(auto_now=True, help_text="DateTime of last modification"),
                ),
                ("release", models.CharField(max_length=32)),
                ("chromosome", models.CharField(max_length=32)),
                ("start", models.IntegerField()),
                ("end", models.IntegerField()),
                ("bin", models.IntegerField()),
                ("reference", models.CharField(max_length=512)),
                ("alternative", models.CharField(max_length=512)),
                ("aa_wildtype", models.CharField(max_length=512)),
                ("aa_mutant", models.CharField(max_length=512)),
                ("gene_name", models.CharField(max_length=512)),
                ("conclusion", models.CharField(max_length=512)),
                ("ensembl_gene_id", models.CharField(max_length=16)),
                ("ensembl_transcript_id", models.CharField(max_length=32)),
                ("pathogenicity_score", models.IntegerField()),
                ("transcript_position", models.IntegerField()),
            ],
            options={"abstract": False},
        ),
        migrations.RenameField(
            model_name="smallvariantqueryvariantscores", old_name="api_result", new_name="info"
        ),
    ]
