# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-03 16:55
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("variants", "0065_projectcasessmallvariantqueryvariantscores")]

    operations = [
        migrations.AddField(
            model_name="case",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=32),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        )
    ]
