# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-12 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid
import variants.models


class Migration(migrations.Migration):

    dependencies = [
        ("projectroles", "0013_update_appsetting_type"),
        ("bgjobs", "0005_auto_20190128_1210"),
        ("variants", "0067_smallvariant_seq_id_bigint"),
    ]

    operations = [
        migrations.CreateModel(
            name="KioskAnnotateBgJob",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, help_text="DateTime of creation"),
                ),
                (
                    "sodar_uuid",
                    models.UUIDField(default=uuid.uuid4, help_text="Job UUID", unique=True),
                ),
                (
                    "path_vcf",
                    models.CharField(help_text="Path to the vcf file to annotate", max_length=4096),
                ),
                (
                    "path_db_info",
                    models.CharField(help_text="Output path to the db info file", max_length=4096),
                ),
                (
                    "path_gts",
                    models.CharField(help_text="Output path to the gts file", max_length=4096),
                ),
                (
                    "path_tmp_dir",
                    models.CharField(help_text="Path to the tmp dir", max_length=4096),
                ),
                (
                    "bg_job",
                    models.ForeignKey(
                        help_text="Background job for state etc.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants_kioskannotatebgjob_related",
                        to="bgjobs.BackgroundJob",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project that is imported to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projectroles.Project",
                    ),
                ),
            ],
            bases=(variants.models.JobModelMessageMixin2, models.Model),
        )
    ]
