# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-26 17:28
from __future__ import unicode_literals

import uuid

import bgjobs.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bgjobs", "0006_auto_20200526_1657"),
        ("variants", "0072_deletecasebgjob"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClearExpiredExportedFilesBgJob",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, help_text="DateTime of creation"),
                ),
                (
                    "sodar_uuid",
                    models.UUIDField(default=uuid.uuid4, help_text="Case SODAR UUID", unique=True),
                ),
                (
                    "bg_job",
                    models.ForeignKey(
                        help_text="Background job for state etc.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants_clearexpiredexportedfilesbgjob_related",
                        to="bgjobs.BackgroundJob",
                    ),
                ),
            ],
            options={
                "ordering": ("-date_created",),
                "abstract": False,
            },
            bases=(bgjobs.models.JobModelMessageMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ClearInactiveVariantSetsBgJob",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, help_text="DateTime of creation"),
                ),
                (
                    "sodar_uuid",
                    models.UUIDField(default=uuid.uuid4, help_text="Case SODAR UUID", unique=True),
                ),
                (
                    "bg_job",
                    models.ForeignKey(
                        help_text="Background job for state etc.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants_clearinactivevariantsetsbgjob_related",
                        to="bgjobs.BackgroundJob",
                    ),
                ),
            ],
            options={
                "ordering": ("-date_created",),
                "abstract": False,
            },
            bases=(bgjobs.models.JobModelMessageMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ClearOldKioskCasesBgJob",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, help_text="DateTime of creation"),
                ),
                (
                    "sodar_uuid",
                    models.UUIDField(default=uuid.uuid4, help_text="Case SODAR UUID", unique=True),
                ),
                (
                    "bg_job",
                    models.ForeignKey(
                        help_text="Background job for state etc.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants_clearoldkioskcasesbgjob_related",
                        to="bgjobs.BackgroundJob",
                    ),
                ),
            ],
            options={
                "ordering": ("-date_created",),
                "abstract": False,
            },
            bases=(bgjobs.models.JobModelMessageMixin, models.Model),
        ),
        migrations.CreateModel(
            name="RefreshSmallVariantSummaryBgJob",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, help_text="DateTime of creation"),
                ),
                (
                    "sodar_uuid",
                    models.UUIDField(default=uuid.uuid4, help_text="Case SODAR UUID", unique=True),
                ),
                (
                    "bg_job",
                    models.ForeignKey(
                        help_text="Background job for state etc.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants_refreshsmallvariantsummarybgjob_related",
                        to="bgjobs.BackgroundJob",
                    ),
                ),
            ],
            options={
                "ordering": ("-date_created",),
                "abstract": False,
            },
            bases=(bgjobs.models.JobModelMessageMixin, models.Model),
        ),
    ]
