# Generated by Django 3.2.4 on 2021-06-17 14:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("variants", "0081_set_logged_table_again"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casealignmentstats",
            name="bam_stats",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="importvariantsbgjob",
            name="path_bam_qc",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(help_text="Path to bam-qc TSV file", max_length=4096),
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="projectcasessmallvariantqueryvariantscores",
            name="info",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="smallvariantqueryvariantscores",
            name="info",
            field=models.JSONField(default=dict),
        ),
    ]
