# Generated by Django 3.2.9 on 2021-11-29 14:43

from django.db import migrations

import varfish.utils


class Migration(migrations.Migration):

    dependencies = [
        ("variants", "0082_auto_20210617_1409"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caddpathogenicityscorecache",
            name="info",
            field=varfish.utils.JSONField(),
        ),
        migrations.AlterField(
            model_name="caddsubmissionbgjob",
            name="query_args",
            field=varfish.utils.JSONField(help_text="(Validated) query parameters"),
        ),
        migrations.AlterField(
            model_name="case",
            name="pedigree",
            field=varfish.utils.JSONField(),
        ),
        migrations.AlterField(
            model_name="casealignmentstats",
            name="bam_stats",
            field=varfish.utils.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="distillersubmissionbgjob",
            name="query_args",
            field=varfish.utils.JSONField(help_text="(Validated) query parameters"),
        ),
        migrations.AlterField(
            model_name="exportfilebgjob",
            name="query_args",
            field=varfish.utils.JSONField(help_text="(Validated) query parameters"),
        ),
        migrations.AlterField(
            model_name="exportprojectcasesfilebgjob",
            name="query_args",
            field=varfish.utils.JSONField(help_text="(Validated) query parameters"),
        ),
        migrations.AlterField(
            model_name="projectcasessmallvariantquery",
            name="query_settings",
            field=varfish.utils.JSONField(help_text="The query settings"),
        ),
        migrations.AlterField(
            model_name="projectcasessmallvariantqueryvariantscores",
            name="info",
            field=varfish.utils.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="samplevariantstatistics",
            name="ontarget_dps",
            field=varfish.utils.JSONField(),
        ),
        migrations.AlterField(
            model_name="samplevariantstatistics",
            name="ontarget_effect_counts",
            field=varfish.utils.JSONField(),
        ),
        migrations.AlterField(
            model_name="samplevariantstatistics",
            name="ontarget_indel_sizes",
            field=varfish.utils.JSONField(),
        ),
        migrations.AlterField(
            model_name="smallvariantquery",
            name="query_settings",
            field=varfish.utils.JSONField(help_text="The query settings"),
        ),
        migrations.AlterField(
            model_name="smallvariantqueryvariantscores",
            name="info",
            field=varfish.utils.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="spanrsubmissionbgjob",
            name="query_args",
            field=varfish.utils.JSONField(help_text="(Validated) query parameters"),
        ),
    ]
