# Generated by Django 3.2.16 on 2022-10-06 13:35

import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("variants", "0086_smallvariantsummary_excludefrominhousedb"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseGeneAnnotationEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "sodar_uuid",
                    models.UUIDField(
                        default=uuid.uuid4, help_text="Record SODAR UUID", unique=True
                    ),
                ),
                (
                    "gene_symbol",
                    models.CharField(help_text="The gene symbol (informative only)", max_length=32),
                ),
                ("entrez_id", models.CharField(help_text="The entrez gene ID", max_length=32)),
                (
                    "ensembl_gene_id",
                    models.CharField(help_text="The ENSEMBL bene ID", max_length=32),
                ),
                ("annotation", models.JSONField(default=dict, help_text="The annotation JSON")),
                (
                    "case",
                    models.ForeignKey(
                        help_text="The annotated case",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="variants.case",
                    ),
                ),
            ],
            options={
                "ordering": ["gene_symbol"],
            },
        ),
    ]
