# Generated by Django 3.2.16 on 2022-11-09 14:26

import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor):
    CasePhenotypeTerms = apps.get_model("variants", "casephenotypeterms")
    for row in CasePhenotypeTerms.objects.all():
        row.sodar_uuid = uuid.uuid4()
        row.save(update_fields=["sodar_uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("variants", "0089_auto_20221109_1426"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
