# Generated by Django 3.2.20 on 2023-07-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("variants", "0093_auto_20230711_1501"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="case_version",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="case",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("importing", "importing"),
                    ("updating", "updating"),
                    ("active", "active"),
                    ("deleting", "deleting"),
                ],
                max_length=128,
                null=True,
            ),
        ),
    ]
