# Generated by Django 3.2.20 on 2023-07-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("variants", "0093_auto_20230711_1501"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="case_version",
            field=models.IntegerField(default=1),
        ),
    ]
