# Generated by Django 3.2.20 on 2023-07-26 09:20

from django.db import migrations


def create_smallvariantqueryresultset_for_case(apps, schema_editor):
    SmallVariantQueryResultSet = apps.get_model("variants", "SmallVariantQueryResultSet")
    Case = apps.get_model("variants", "Case")
    for case in Case.objects.all():
        SmallVariantQueryResultSet.objects.create(
            case=case,
            result_row_count=0,
            start_time=case.date_created,
            end_time=case.date_created,
            elapsed_seconds=0,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("variants", "0095_auto_20230724_0820"),
    ]

    operations = [
        migrations.RunPython(create_smallvariantqueryresultset_for_case),
    ]
