# Generated by Django 3.2.24 on 2024-03-01 11:41

import uuid

from django.db import migrations, models


def gen_uuid(apps, schema_editor):
    for model_name in ("AnnotationReleaseInfo", "SmallVariantSet"):
        model_class = apps.get_model("variants", model_name)
        for row in model_class.objects.all():
            row.sodar_uuid = uuid.uuid4()
            row.save(update_fields=["sodar_uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("variants", "0099_auto_20240301_1141_nullable_sodar_uuid"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
