# Generated by Django 3.2.24 on 2024-03-01 11:59

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("variants", "0100_auto_20240301_1141_fill_sodar_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotationreleaseinfo",
            name="sodar_uuid",
            field=models.UUIDField(
                default=uuid.uuid4, help_text="Small variant flags SODAR UUID", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="smallvariantset",
            name="sodar_uuid",
            field=models.UUIDField(
                default=uuid.uuid4, help_text="Small variant flags SODAR UUID", unique=True
            ),
        ),
    ]
