# Generated by Django 3.2.25 on 2024-05-15 12:50

from django.db import migrations


def clear_query_settings(apps, schema_editor):
    SmallVariantQuery = apps.get_model("variants", "SmallVariantQuery")
    for s in SmallVariantQuery.objects.all():
        save = False
        if "remove_if_in_dbsnp" in s.query_settings:
            del s.query_settings["remove_if_in_dbsnp"]
            save = True
        if "require_in_hgmd_public" in s.query_settings:
            del s.query_settings["require_in_hgmd_public"]
            save = True
        if save:
            s.save()


class Migration(migrations.Migration):

    dependencies = [
        ("variants", "0103_presetset_default_presetset"),
    ]

    operations = [
        migrations.RunPython(clear_query_settings, lambda _x, _y: None),
    ]
