# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-23 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("genomicfeatures", "0001_initial")]

    operations = [
        migrations.AddIndex(
            model_name="geneinterval",
            index=models.Index(fields=["gene_id"], name="genomicfeat_gene_id_87aab6_idx"),
        )
    ]
