# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-19 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("genomicfeatures", "0002_auto_20190523_1346")]

    operations = [
        migrations.RemoveIndex(
            model_name="ensemblregulatoryfeature", name="genomicfeat_release_3adf69_gin"
        ),
        migrations.RemoveIndex(model_name="geneinterval", name="genomicfeat_databas_a312b0_gin"),
        migrations.RemoveIndex(
            model_name="tadboundaryinterval", name="genomicfeat_release_63da73_gin"
        ),
        migrations.RemoveIndex(model_name="tadinterval", name="genomicfeat_release_a530cc_gin"),
        migrations.RemoveIndex(model_name="vistaenhancer", name="genomicfeat_release_d51359_gin"),
        migrations.RemoveField(model_name="ensemblregulatoryfeature", name="containing_bins"),
        migrations.RemoveField(model_name="geneinterval", name="containing_bins"),
        migrations.RemoveField(model_name="tadboundaryinterval", name="containing_bins"),
        migrations.RemoveField(model_name="tadinterval", name="containing_bins"),
        migrations.RemoveField(model_name="vistaenhancer", name="containing_bins"),
    ]
