# Generated by Django 3.2.4 on 2021-06-17 14:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("svdbs", "0003_auto_20190723_0934"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dgvgoldstandardsvs",
            name="sv_sub_type",
            field=models.CharField(
                choices=[
                    ("gain", "gain"),
                    ("loss", "loss"),
                    ("gain+loss", "gain+loss"),
                    ("insertion", "insertion"),
                    ("novel sequence insertion", "novel sequence insertion"),
                    ("deletion", "deletion"),
                    ("complex", "complex"),
                    ("sequence alteration", "sequence alteration"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="gnomadsv",
            name="alt",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64), default=list, size=None
            ),
        ),
    ]
