# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-24 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("conservation", "0002_auto_20190619_0926")]

    operations = [
        migrations.AddField(
            model_name="knowngeneaa",
            name="bin",
            field=models.IntegerField(default=0),
            preserve_default=False,
        )
    ]
