# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-05 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("dbsnp", "0002_auto_20190619_1636")]

    operations = [migrations.RemoveIndex(model_name="dbsnp", name="dbsnp_dbsnp_release_8ac946_idx")]
