# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-13 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExtraAnno",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("release", models.CharField(max_length=32)),
                ("chromosome", models.CharField(max_length=32)),
                ("start", models.IntegerField()),
                ("end", models.IntegerField()),
                ("bin", models.IntegerField()),
                ("reference", models.CharField(max_length=512)),
                ("alternative", models.CharField(max_length=512)),
                ("anno_data", models.JSONField(default={})),
            ],
        ),
        migrations.CreateModel(
            name="ExtraAnnoField",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("field", models.IntegerField()),
                ("label", models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="extraanno",
            unique_together=set([("release", "chromosome", "start", "reference", "alternative")]),
        ),
    ]
