# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-14 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("extra_annos", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="extraannofield",
            options={"ordering": ("field",)},
        ),
    ]
