# Generated by Django 3.2.9 on 2021-11-29 14:43

from django.db import migrations

import varfish.utils


class Migration(migrations.Migration):

    dependencies = [
        ("extra_annos", "0003_alter_extraanno_anno_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extraanno",
            name="anno_data",
            field=varfish.utils.JSONField(default=dict),
        ),
    ]
