// This file is auto-generated by @hey-api/openapi-ts

import { client, type Options } from '@hey-api/client-fetch';
import type { HpoGenesData, HpoGenesError, HpoGenesResponse, HpoOmimsData, HpoOmimsError, HpoOmimsResponse, HpoSimTermGeneData, HpoSimTermGeneError, HpoSimTermGeneResponse, HpoSimTermTermData, HpoSimTermTermError, HpoSimTermTermResponse, HpoTermsData, HpoTermsError, HpoTermsResponse } from './types.gen';

export class HpoGenesService {
    /**
     * Query for genes in the HPO database.
     */
    public static hpoGenes(options?: Options<HpoGenesData>) {
        return (options?.client ?? client).get<HpoGenesResponse, HpoGenesError>({
            ...options,
            url: '/hpo/genes'
        });
    }
    
}

export class HpoOmimsService {
    /**
     * Query for OMIM diseases in the HPO database.
     */
    public static hpoOmims(options?: Options<HpoOmimsData>) {
        return (options?.client ?? client).get<HpoOmimsResponse, HpoOmimsError>({
            ...options,
            url: '/hpo/omims'
        });
    }
    
}

export class HpoSimTermGeneService {
    /**
     * Query for similarity between a set of terms to each entry in a
     * list of genes.
     */
    public static hpoSimTermGene(options: Options<HpoSimTermGeneData>) {
        return (options?.client ?? client).get<HpoSimTermGeneResponse, HpoSimTermGeneError>({
            ...options,
            url: '/hpo/sim/term-gene'
        });
    }
    
}

export class HpoSimTermTermService {
    /**
     * Query for pairwise term similarity.
     * In the case of Resnik, this corresponds to `IC(MICA(t_1, t_2))`.
     *
     * # Errors
     *
     * In the case that there is an error running the server.
     */
    public static hpoSimTermTerm(options: Options<HpoSimTermTermData>) {
        return (options?.client ?? client).get<HpoSimTermTermResponse, HpoSimTermTermError>({
            ...options,
            url: '/hpo/sim/term-term'
        });
    }
    
}

export class HpoTermsService {
    /**
     * Query for terms in the HPO database.
     * # Errors
     *
     * In the case that there is an error running the server.
     */
    public static hpoTerms(options?: Options<HpoTermsData>) {
        return (options?.client ?? client).get<HpoTermsResponse, HpoTermsError>({
            ...options,
            url: '/hpo/terms'
        });
    }
    
}