# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-07 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projectroles", "0017_project_full_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, help_text="DateTime of creation"),
                ),
                (
                    "date_modified",
                    models.DateTimeField(auto_now=True, help_text="DateTime of last modification"),
                ),
                ("title", models.CharField(max_length=512)),
                ("filename", models.CharField(max_length=512)),
                ("filesize", models.IntegerField(default=0)),
                ("filehash", models.CharField(max_length=128)),
                (
                    "sodar_uuid",
                    models.UUIDField(default=uuid.uuid4, help_text="Case SODAR UUID", unique=True),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project in which this objects belongs",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projectroles.Project",
                    ),
                ),
            ],
            options={"ordering": ("title",),},
        ),
        migrations.AlterUniqueTogether(
            name="reporttemplate", unique_together=set([("project", "filename")]),
        ),
    ]
