# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-19 10:45
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release', models.CharField(max_length=32)),
                ('chromosome', models.CharField(max_length=32)),
                ('position', models.IntegerField()),
                ('reference', models.CharField(max_length=512)),
                ('alternative', models.CharField(max_length=512)),
                ('database', models.CharField(max_length=8, null=True)),
                ('effect', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64, null=True), size=None)),
                ('gene_id', models.CharField(max_length=64, null=True)),
                ('transcript_id', models.CharField(max_length=64, null=True)),
                ('transcript_coding', models.NullBooleanField()),
                ('hgvs_c', models.CharField(max_length=512, null=True)),
                ('hgvs_p', models.CharField(max_length=512, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['release', 'chromosome', 'position', 'reference', 'alternative', 'gene_id'], name='annotation__release_3f254e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='annotation',
            unique_together=set([('release', 'chromosome', 'position', 'reference', 'alternative', 'transcript_id')]),
        ),
    ]
