# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-12 11:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("annotation", "0001_initial")]

    operations = [
        migrations.RunSQL(
            r"""ALTER TABLE "annotation_annotation" ALTER COLUMN "id" TYPE bigint USING "id"::bigint"""
        )
    ]
