# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-19 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("annotation", "0002_annotation_bigint_id_field")]

    operations = [
        migrations.RemoveIndex(model_name="annotation", name="annotation__release_3f254e_idx"),
        migrations.RenameField(model_name="annotation", old_name="position", new_name="start"),
        migrations.AddField(
            model_name="annotation",
            name="bin",
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="annotation",
            name="end",
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="annotation",
            unique_together=set(
                [("release", "chromosome", "start", "reference", "alternative", "transcript_id")]
            ),
        ),
        migrations.AddIndex(
            model_name="annotation",
            index=models.Index(
                fields=["release", "chromosome", "start", "reference", "alternative", "gene_id"],
                name="annotation__release_ea833d_idx",
            ),
        ),
    ]
