# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-15 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("annotation", "0003_auto_20190619_1636")]

    operations = [migrations.DeleteModel(name="Annotation")]
