# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-19 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImportInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("table", models.CharField(max_length=16)),
                ("timestamp", models.DateTimeField(editable=False)),
                ("release", models.CharField(max_length=16)),
                ("comment", models.CharField(max_length=1024)),
            ],
        )
    ]
