# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-13 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("importer", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="importinfo", name="release", field=models.CharField(max_length=512)
        )
    ]
