# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-15 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("importer", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="importinfo",
            name="genomebuild",
            field=models.CharField(default="GRCh37", max_length=32),
        ),
        migrations.AlterField(
            model_name="importinfo", name="release", field=models.CharField(max_length=512)
        ),
        migrations.AlterField(
            model_name="importinfo", name="timestamp", field=models.DateTimeField(auto_now_add=True)
        ),
        migrations.AlterUniqueTogether(
            name="importinfo", unique_together=set([("genomebuild", "table", "release")])
        ),
    ]
