# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-09 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("importer", "0002_auto_20190215_1744")]

    operations = [
        migrations.AlterField(
            model_name="importinfo", name="table", field=models.CharField(max_length=512)
        )
    ]
