# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-13 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("importer", "0002_auto_20190213_1150")]

    operations = [
        migrations.AlterUniqueTogether(
            name="importinfo", unique_together=set([("table", "release")])
        )
    ]
