# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-15 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("importer", "0003_auto_20190409_1101")]

    operations = [
        migrations.AlterUniqueTogether(
            name="importinfo", unique_together=set([("genomebuild", "table")])
        )
    ]
