# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-30 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("importer", "0005_auto_20200129_1600"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caseimportinfo",
            name="state",
            field=models.CharField(
                choices=[
                    ("draft", "draft"),
                    ("submitted", "submitted"),
                    ("imported", "imported"),
                    ("evicted", "evicted"),
                    ("failed", "failed"),
                ],
                default="draft",
                help_text="State of the case import ",
                max_length=32,
            ),
        ),
    ]
