# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-15 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("importer", "0007_auto_20200203_1242"),
    ]

    operations = [
        migrations.AddField(
            model_name="variantsetimportinfo",
            name="state",
            field=models.CharField(
                choices=[
                    ("draft", "draft"),
                    ("uploaded", "uploaded"),
                    ("imported", "imported"),
                    ("evicted", "evicted"),
                    ("failed", "failed"),
                ],
                default="draft",
                help_text="State of the variant set import",
                max_length=32,
            ),
        ),
    ]
