# Generated by Django 3.2.9 on 2021-11-29 14:43

from django.db import migrations

import varfish.utils


class Migration(migrations.Migration):
    dependencies = [
        ("importer", "0008_variantsetimportinfo_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caseimportinfo",
            name="pedigree",
            field=varfish.utils.JSONField(),
        ),
    ]
