# Generated by Django 3.2.7 on 2022-01-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("importer", "0009_alter_caseimportinfo_pedigree"),
    ]

    operations = [
        migrations.AddField(
            model_name="caseimportinfo",
            name="release",
            field=models.CharField(default="GRCh37", max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="variantsetimportinfo",
            name="genomebuild",
            field=models.CharField(
                choices=[("GRCh37", "GRCh37"), ("GRCh38", "GRCh38")],
                default="GRCh37",
                help_text="Genome build used in the variant set.",
                max_length=32,
            ),
        ),
    ]
