# Generated by Django 3.2.16 on 2022-10-06 14:45

import uuid

from django.db import migrations, models
import django.db.models.deletion

import importer.models


class Migration(migrations.Migration):

    dependencies = [
        ("importer", "0010_auto_20220112_0657"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseGeneAnnotationFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "sodar_uuid",
                    models.UUIDField(default=uuid.uuid4, help_text="Record UUID", unique=True),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, help_text="DateTime of creation"),
                ),
                (
                    "date_modified",
                    models.DateTimeField(auto_now=True, help_text="DateTime of last modification"),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="The uploaded file.",
                        upload_to=importer.models.set_member_file_url_upload_to,
                    ),
                ),
                ("name", models.CharField(help_text="Original file name.", max_length=200)),
                (
                    "md5",
                    models.CharField(help_text="MD5 checksum of original file.", max_length=32),
                ),
                (
                    "case_import_info",
                    models.ForeignKey(
                        help_text="The case import info that this is for.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="importer.caseimportinfo",
                    ),
                ),
            ],
            options={
                "unique_together": {("case_import_info", "md5")},
            },
        ),
    ]
