# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-19 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KnowngeneAA",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("chromosome", models.CharField(max_length=16)),
                ("start", models.IntegerField()),
                ("end", models.IntegerField()),
                ("transcript_id", models.CharField(max_length=16)),
                ("alignment", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddIndex(
            model_name="knowngeneaa",
            index=models.Index(
                fields=["chromosome", "start", "end"], name="conservatio_chromos_a742d8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="knowngeneaa",
            unique_together=set([("chromosome", "start", "end", "transcript_id")]),
        ),
    ]
