# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-19 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("conservation", "0001_initial")]

    operations = [
        migrations.RemoveIndex(model_name="knowngeneaa", name="conservatio_chromos_a742d8_idx"),
        migrations.AddField(
            model_name="knowngeneaa",
            name="release",
            field=models.CharField(default="GRCh37", max_length=32),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="knowngeneaa",
            unique_together=set([("release", "chromosome", "start", "end", "transcript_id")]),
        ),
        migrations.AddIndex(
            model_name="knowngeneaa",
            index=models.Index(
                fields=["release", "chromosome", "start", "end"],
                name="conservatio_release_ce232d_idx",
            ),
        ),
    ]
