# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-01-06 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("conservation", "0003_knowngeneaa_bin")]

    operations = [
        migrations.AddField(
            model_name="knowngeneaa",
            name="transcript_id_novers",
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddIndex(
            model_name="knowngeneaa",
            index=models.Index(
                fields=["transcript_id_novers"], name="conservatio_transcr_8aa7d7_idx"
            ),
        ),
    ]
