# Generated by Django 3.2.20 on 2023-07-12 11:10

import uuid

from django.db import migrations, models
import django.db.models.deletion

import varfish.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projectroles", "0021_remove_project_submit_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseImportAction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sodar_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[("create", "create"), ("update", "update"), ("delete", "delete")],
                        default="create",
                        max_length=32,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("submitted", "submitted"),
                            ("running", "running"),
                            ("failed", "failed"),
                            ("success", "success"),
                        ],
                        default="draft",
                        max_length=32,
                    ),
                ),
                ("payload", varfish.utils.JSONField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="projectroles.project"
                    ),
                ),
            ],
            options={
                "ordering": ("-date_modified",),
            },
        ),
    ]
