# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gnomad',
            new_name='GnomadExomes',
        ),
        migrations.RemoveIndex(
            model_name='gnomadexomes',
            name='main_gnomad_release_68daa9_idx',
        ),
        migrations.AddIndex(
            model_name='gnomadexomes',
            index=models.Index(fields=['release', 'chromosome', 'position', 'reference', 'alternative'], name='main_gnomad_release_50df5f_idx'),
        ),
    ]
