# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180925_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='index',
            field=models.CharField(default='XXX', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterUniqueTogether(
            name='case',
            unique_together=set([('name', 'index')]),
        ),
    ]
