# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-04 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180928_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='GnomadGenomes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release', models.CharField(max_length=32)),
                ('chromosome', models.CharField(max_length=32)),
                ('position', models.IntegerField()),
                ('reference', models.CharField(max_length=512)),
                ('alternative', models.CharField(max_length=512)),
                ('ac', models.IntegerField(null=True)),
                ('ac_afr', models.IntegerField(null=True)),
                ('ac_amr', models.IntegerField(null=True)),
                ('ac_asj', models.IntegerField(null=True)),
                ('ac_eas', models.IntegerField(null=True)),
                ('ac_fin', models.IntegerField(null=True)),
                ('ac_nfe', models.IntegerField(null=True)),
                ('ac_oth', models.IntegerField(null=True)),
                ('an', models.IntegerField(null=True)),
                ('an_afr', models.IntegerField(null=True)),
                ('an_amr', models.IntegerField(null=True)),
                ('an_asj', models.IntegerField(null=True)),
                ('an_eas', models.IntegerField(null=True)),
                ('an_fin', models.IntegerField(null=True)),
                ('an_nfe', models.IntegerField(null=True)),
                ('an_oth', models.IntegerField(null=True)),
                ('hemi', models.IntegerField(null=True)),
                ('hemi_afr', models.IntegerField(null=True)),
                ('hemi_amr', models.IntegerField(null=True)),
                ('hemi_asj', models.IntegerField(null=True)),
                ('hemi_eas', models.IntegerField(null=True)),
                ('hemi_fin', models.IntegerField(null=True)),
                ('hemi_nfe', models.IntegerField(null=True)),
                ('hemi_oth', models.IntegerField(null=True)),
                ('hom', models.IntegerField(null=True)),
                ('hom_afr', models.IntegerField(null=True)),
                ('hom_amr', models.IntegerField(null=True)),
                ('hom_asj', models.IntegerField(null=True)),
                ('hom_eas', models.IntegerField(null=True)),
                ('hom_fin', models.IntegerField(null=True)),
                ('hom_nfe', models.IntegerField(null=True)),
                ('hom_oth', models.IntegerField(null=True)),
                ('popmax', models.CharField(max_length=8, null=True)),
                ('ac_popmax', models.IntegerField(null=True)),
                ('an_popmax', models.IntegerField(null=True)),
                ('af_popmax', models.FloatField(null=True)),
                ('hemi_popmax', models.IntegerField(null=True)),
                ('hom_popmax', models.IntegerField(null=True)),
                ('af', models.FloatField(null=True)),
                ('af_afr', models.FloatField(null=True)),
                ('af_amr', models.FloatField(null=True)),
                ('af_asj', models.FloatField(null=True)),
                ('af_eas', models.FloatField(null=True)),
                ('af_fin', models.FloatField(null=True)),
                ('af_nfe', models.FloatField(null=True)),
                ('af_oth', models.FloatField(null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='gnomadgenomes',
            index=models.Index(fields=['release', 'chromosome', 'position', 'reference', 'alternative'], name='main_gnomad_release_53aa6f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gnomadgenomes',
            unique_together=set([('release', 'chromosome', 'position', 'reference', 'alternative')]),
        ),
    ]
