# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-11 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181004_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThousandGenomes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release', models.CharField(max_length=32)),
                ('chromosome', models.CharField(max_length=32)),
                ('position', models.IntegerField()),
                ('reference', models.CharField(max_length=512)),
                ('alternative', models.CharField(max_length=512)),
                ('ac', models.IntegerField(null=True)),
                ('an', models.IntegerField(null=True)),
                ('het', models.IntegerField(null=True)),
                ('hom', models.IntegerField(null=True)),
                ('af', models.FloatField(null=True)),
                ('af_afr', models.FloatField(null=True)),
                ('af_amr', models.FloatField(null=True)),
                ('af_eas', models.FloatField(null=True)),
                ('af_eur', models.FloatField(null=True)),
                ('af_sas', models.FloatField(null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='thousandgenomes',
            index=models.Index(fields=['release', 'chromosome', 'position', 'reference', 'alternative'], name='main_thousa_release_77a14f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='thousandgenomes',
            unique_together=set([('release', 'chromosome', 'position', 'reference', 'alternative')]),
        ),
    ]
