# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-16 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projectroles', '0005_update_uuid'),
        ('main', '0005_auto_20181011_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='project',
            field=models.ForeignKey(default='', help_text='Project in which this objects belongs', on_delete=django.db.models.deletion.CASCADE, to='projectroles.Project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='sodar_uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='Case SODAR UUID', unique=True),
        ),
        migrations.AddField(
            model_name='smallvariant',
            name='project',
            field=models.ForeignKey(default='', help_text='Project in which this objects belongs', on_delete=django.db.models.deletion.CASCADE, to='projectroles.Project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smallvariant',
            name='sodar_uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='SmallVariant SODAR UUID', unique=True),
        ),
    ]
