# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-17 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20181016_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='uuid',
        ),
    ]
