# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-17 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_case_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smallvariant',
            name='project',
        ),
        migrations.RemoveField(
            model_name='smallvariant',
            name='sodar_uuid',
        ),
    ]
