# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-05 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("frequencies", "0002_auto_20190619_1636")]

    operations = [
        migrations.RemoveIndex(model_name="exac", name="frequencies_release_d330e5_idx"),
        migrations.RemoveIndex(model_name="gnomadexomes", name="frequencies_release_d5febf_idx"),
        migrations.RemoveIndex(model_name="gnomadgenomes", name="frequencies_release_a0fce9_idx"),
        migrations.RemoveIndex(model_name="thousandgenomes", name="frequencies_release_f3feb8_idx"),
    ]
