# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-07 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("frequencies", "0003_auto_20190705_1321")]

    operations = [
        migrations.AddField(
            model_name="gnomadexomes", name="controls_ac", field=models.IntegerField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadexomes", name="controls_ac_afr", field=models.IntegerField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadexomes", name="controls_ac_amr", field=models.IntegerField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadexomes", name="controls_ac_asj", field=models.IntegerField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadexomes", name="controls_ac_eas", field=models.IntegerField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadexomes", name="controls_ac_fin", field=models.IntegerField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadexomes", name="controls_ac_nfe", field=models.IntegerField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadexomes", name="controls_ac_oth", field=models.IntegerField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadexomes",
            name="controls_ac_popmax",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="gnomadexomes", name="controls_ac_sas", field=models.IntegerField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadexomes", name="controls_af", field=models.FloatField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadexomes", name="controls_af_afr", field=models.FloatField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadexomes", name="controls_af_amr", field=models.FloatField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadexomes", name="controls_af_asj", field=models.FloatField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadexomes", name="controls_af_eas", field=models.FloatField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadexomes", name="controls_af_fin", field=models.FloatField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadexomes", name="controls_af_nfe", field=models.FloatField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadexomes", name="controls_af_oth", field=models.FloatField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadexomes", name="controls_af_popmax", field=models.FloatField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadexomes", name="controls_af_sas", field=models.FloatField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadexomes", name="controls_an", field=models.IntegerField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadexomes", name="controls_an_afr", field=models.IntegerField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadexomes", name="controls_an_amr", field=models.IntegerField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadexomes", name="controls_an_asj", field=models.IntegerField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadexomes", name="controls_an_eas", field=models.IntegerField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadexomes", name="controls_an_fin", field=models.IntegerField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadexomes", name="controls_an_nfe", field=models.IntegerField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadexomes", name="controls_an_oth", field=models.IntegerField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadexomes",
            name="controls_an_popmax",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="gnomadexomes", name="controls_an_sas", field=models.IntegerField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadexomes", name="controls_hemi", field=models.IntegerField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadexomes",
            name="controls_hemi_afr",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="gnomadexomes",
            name="controls_hemi_amr",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="gnomadexomes",
            name="controls_hemi_asj",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="gnomadexomes",
            name="controls_hemi_eas",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="gnomadexomes",
            name="controls_hemi_fin",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="gnomadexomes",
            name="controls_hemi_nfe",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="gnomadexomes",
            name="controls_hemi_oth",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="gnomadexomes",
            name="controls_hemi_popmax",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="gnomadexomes",
            name="controls_hemi_sas",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="gnomadexomes", name="controls_hom", field=models.IntegerField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadexomes", name="controls_hom_afr", field=models.IntegerField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadexomes", name="controls_hom_amr", field=models.IntegerField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadexomes", name="controls_hom_asj", field=models.IntegerField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadexomes", name="controls_hom_eas", field=models.IntegerField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadexomes", name="controls_hom_fin", field=models.IntegerField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadexomes", name="controls_hom_nfe", field=models.IntegerField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadexomes", name="controls_hom_oth", field=models.IntegerField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadexomes",
            name="controls_hom_popmax",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="gnomadexomes", name="controls_hom_sas", field=models.IntegerField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadexomes",
            name="controls_popmax",
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="gnomadgenomes", name="controls_ac", field=models.IntegerField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadgenomes", name="controls_ac_afr", field=models.IntegerField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadgenomes", name="controls_ac_amr", field=models.IntegerField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadgenomes", name="controls_ac_asj", field=models.IntegerField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadgenomes", name="controls_ac_eas", field=models.IntegerField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadgenomes", name="controls_ac_fin", field=models.IntegerField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadgenomes", name="controls_ac_nfe", field=models.IntegerField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadgenomes", name="controls_ac_oth", field=models.IntegerField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadgenomes",
            name="controls_ac_popmax",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="gnomadgenomes", name="controls_af", field=models.FloatField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadgenomes", name="controls_af_afr", field=models.FloatField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadgenomes", name="controls_af_amr", field=models.FloatField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadgenomes", name="controls_af_asj", field=models.FloatField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadgenomes", name="controls_af_eas", field=models.FloatField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadgenomes", name="controls_af_fin", field=models.FloatField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadgenomes", name="controls_af_nfe", field=models.FloatField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadgenomes", name="controls_af_oth", field=models.FloatField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadgenomes",
            name="controls_af_popmax",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="gnomadgenomes", name="controls_an", field=models.IntegerField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadgenomes", name="controls_an_afr", field=models.IntegerField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadgenomes", name="controls_an_amr", field=models.IntegerField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadgenomes", name="controls_an_asj", field=models.IntegerField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadgenomes", name="controls_an_eas", field=models.IntegerField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadgenomes", name="controls_an_fin", field=models.IntegerField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadgenomes", name="controls_an_nfe", field=models.IntegerField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadgenomes", name="controls_an_oth", field=models.IntegerField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadgenomes",
            name="controls_an_popmax",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="gnomadgenomes", name="controls_hemi", field=models.IntegerField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadgenomes",
            name="controls_hemi_afr",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="gnomadgenomes",
            name="controls_hemi_amr",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="gnomadgenomes",
            name="controls_hemi_asj",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="gnomadgenomes",
            name="controls_hemi_eas",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="gnomadgenomes",
            name="controls_hemi_fin",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="gnomadgenomes",
            name="controls_hemi_nfe",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="gnomadgenomes",
            name="controls_hemi_oth",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="gnomadgenomes",
            name="controls_hemi_popmax",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="gnomadgenomes", name="controls_hom", field=models.IntegerField(null=True)
        ),
        migrations.AddField(
            model_name="gnomadgenomes",
            name="controls_hom_afr",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="gnomadgenomes",
            name="controls_hom_amr",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="gnomadgenomes",
            name="controls_hom_asj",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="gnomadgenomes",
            name="controls_hom_eas",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="gnomadgenomes",
            name="controls_hom_fin",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="gnomadgenomes",
            name="controls_hom_nfe",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="gnomadgenomes",
            name="controls_hom_oth",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="gnomadgenomes",
            name="controls_hom_popmax",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="gnomadgenomes",
            name="controls_popmax",
            field=models.CharField(max_length=8, null=True),
        ),
    ]
