# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-03 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("frequencies", "0005_auto_20200123_1033"),
    ]

    operations = [
        migrations.RemoveField(model_name="mtdb", name="gap",),
    ]
