# Generated by Django 3.2.12 on 2022-08-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frequencies", "0008_alter_mtdb_synonymous"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="helixmtdb",
            index=models.Index(
                fields=["release", "chromosome", "start", "reference", "alternative"],
                name="frequencies_release_a36575_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mitomap",
            index=models.Index(
                fields=["release", "chromosome", "start", "reference", "alternative"],
                name="frequencies_release_126cd0_idx",
            ),
        ),
    ]
