# Generated by Django 3.2.20 on 2023-07-19 11:57

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExternalFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sodar_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("path", models.CharField(max_length=1024, unique=True)),
                ("checksum", models.CharField(max_length=128)),
                (
                    "designation",
                    models.CharField(
                        choices=[
                            ("sequencing_targets", "sequencing_targets"),
                            ("read_alignments", "read_alignments"),
                            ("variant_calls", "variant_calls"),
                            ("other", "other"),
                        ],
                        max_length=128,
                    ),
                ),
                (
                    "genomebuild",
                    models.CharField(
                        choices=[("grch37", "grch37"), ("grch38", "grch38")],
                        max_length=128,
                        null=True,
                    ),
                ),
                ("mimetype", models.CharField(max_length=128)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InternalFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sodar_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("path", models.CharField(max_length=1024, unique=True)),
                ("checksum", models.CharField(max_length=128)),
                (
                    "designation",
                    models.CharField(
                        choices=[
                            ("sequencing_targets", "sequencing_targets"),
                            ("read_alignments", "read_alignments"),
                            ("variant_calls", "variant_calls"),
                            ("other", "other"),
                        ],
                        max_length=128,
                    ),
                ),
                (
                    "genomebuild",
                    models.CharField(
                        choices=[("grch37", "grch37"), ("grch38", "grch38")],
                        max_length=128,
                        null=True,
                    ),
                ),
                ("mimetype", models.CharField(max_length=128)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
