# Generated by Django 3.2.21 on 2023-09-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases_files", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="individualexternalfile",
            name="designation",
            field=models.CharField(
                choices=[
                    ("sequencing_targets", "sequencing_targets"),
                    ("read_alignments", "read_alignments"),
                    ("variant_calls", "variant_calls"),
                    ("quality_control", "quality_control"),
                    ("other", "other"),
                ],
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="individualinternalfile",
            name="designation",
            field=models.CharField(
                choices=[
                    ("sequencing_targets", "sequencing_targets"),
                    ("read_alignments", "read_alignments"),
                    ("variant_calls", "variant_calls"),
                    ("quality_control", "quality_control"),
                    ("other", "other"),
                ],
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="pedigreeexternalfile",
            name="designation",
            field=models.CharField(
                choices=[
                    ("sequencing_targets", "sequencing_targets"),
                    ("read_alignments", "read_alignments"),
                    ("variant_calls", "variant_calls"),
                    ("quality_control", "quality_control"),
                    ("other", "other"),
                ],
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="pedigreeinternalfile",
            name="designation",
            field=models.CharField(
                choices=[
                    ("sequencing_targets", "sequencing_targets"),
                    ("read_alignments", "read_alignments"),
                    ("variant_calls", "variant_calls"),
                    ("quality_control", "quality_control"),
                    ("other", "other"),
                ],
                max_length=128,
            ),
        ),
    ]
