# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-01 07:52
from __future__ import unicode_literals

from django.contrib.postgres.operations import BtreeGinExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("variants", "0004_auto_20181031_1607")]

    operations = [BtreeGinExtension()]
