# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-08 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("variants", "0006_auto_20181106_1022")]

    operations = [
        migrations.AddIndex(
            model_name="smallvariant",
            index=models.Index(
                fields=["case_id", "in_clinvar"], name="variants_sm_case_id_423a80_idx"
            ),
        )
    ]
