# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 09:11
from __future__ import unicode_literals

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("variants", "0020_auto_20181126_1930"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectCasesSmallVariantQuery",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, help_text="DateTime of creation"),
                ),
                (
                    "sodar_uuid",
                    models.UUIDField(
                        default=uuid.uuid4, help_text="Small variant flags SODAR UUID", unique=True
                    ),
                ),
                ("form_id", models.CharField(help_text="Identifier of the form", max_length=100)),
                ("form_version", models.IntegerField(help_text="Version of form when saving")),
                (
                    "query_settings",
                    models.JSONField(help_text="The query settings"),
                ),
                (
                    "name",
                    models.CharField(
                        default=None,
                        help_text="Optional user-assigned name",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "public",
                    models.BooleanField(
                        default=False, help_text="Case is flagged as public or not"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="The case that the query relates to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="small_variant_queries",
                        to="variants.CaseAwareProject",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the query",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="variants_projectcasessmallvariantquery_related",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ("-date_created",), "abstract": False},
        ),
        migrations.AlterModelOptions(
            name="smallvariantquery", options={"ordering": ("-date_created",)}
        ),
        migrations.AlterField(
            model_name="smallvariantquery",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the query",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="variants_smallvariantquery_related",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
