# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("variants", "0022_auto_20181127_1110")]

    operations = [
        migrations.AddIndex(
            model_name="smallvariant",
            index=models.Index(
                fields=["case_id", "ensembl_gene_id", "refseq_gene_id"],
                name="variants_sm_case_id_e96e11_idx",
            ),
        )
    ]
