# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-07 07:23
from __future__ import unicode_literals

import uuid

import bgjobs.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bgjobs", "0005_auto_20190128_1210"),
        ("projectroles", "0006_add_remote_projects"),
        ("variants", "0029_auto_20190306_0727"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinvarBgJob",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "sodar_uuid",
                    models.UUIDField(default=uuid.uuid4, help_text="Case SODAR UUID", unique=True),
                ),
                (
                    "bg_job",
                    models.ForeignKey(
                        help_text="Background job for clinvar filtering and storing query results",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinvar_bg_job",
                        to="bgjobs.BackgroundJob",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        help_text="The case to filter",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="variants.Case",
                    ),
                ),
            ],
            bases=(bgjobs.models.JobModelMessageMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ClinvarQuery",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, help_text="DateTime of creation"),
                ),
                (
                    "sodar_uuid",
                    models.UUIDField(
                        default=uuid.uuid4, help_text="Small variant flags SODAR UUID", unique=True
                    ),
                ),
                ("form_id", models.CharField(help_text="Identifier of the form", max_length=100)),
                ("form_version", models.IntegerField(help_text="Version of form when saving")),
                (
                    "query_settings",
                    models.JSONField(help_text="The query settings"),
                ),
                (
                    "name",
                    models.CharField(
                        default=None,
                        help_text="Optional user-assigned name",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "public",
                    models.BooleanField(
                        default=False, help_text="Case is flagged as public or not"
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        help_text="The case that the query relates to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinvar_queries",
                        to="variants.Case",
                    ),
                ),
                ("query_results", models.ManyToManyField(to="variants.SmallVariant")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the query",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="variants_clinvarquery_related",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ("-date_created",), "abstract": False},
        ),
        migrations.AlterField(
            model_name="projectcasessmallvariantquery",
            name="project",
            field=models.ForeignKey(
                help_text="The project that the query relates to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="small_variant_queries",
                to="variants.CaseAwareProject",
            ),
        ),
        migrations.AddField(
            model_name="clinvarbgjob",
            name="clinvarquery",
            field=models.ForeignKey(
                help_text="Query that is executed.",
                on_delete=django.db.models.deletion.CASCADE,
                to="variants.ClinvarQuery",
            ),
        ),
        migrations.AddField(
            model_name="clinvarbgjob",
            name="project",
            field=models.ForeignKey(
                help_text="Project in which this objects belongs",
                on_delete=django.db.models.deletion.CASCADE,
                to="projectroles.Project",
            ),
        ),
    ]
