# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-24 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("variants", "0033_smallvariantsummary")]

    operations = [
        migrations.CreateModel(
            name="SmallVariantQueryVariantScores",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("release", models.CharField(max_length=32)),
                ("chromosome", models.CharField(max_length=32)),
                ("position", models.IntegerField()),
                ("reference", models.CharField(max_length=512)),
                ("alternative", models.CharField(max_length=512)),
                ("score_type", models.CharField(help_text="The score type", max_length=64)),
                ("score", models.FloatField(help_text="The variant score")),
                (
                    "query",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="variants.SmallVariantQuery"
                    ),
                ),
            ],
        )
    ]
