# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-28 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("variants", "0054_set_unlogged_table")]

    operations = [
        migrations.RemoveField(model_name="clinvarbgjob", name="bg_job"),
        migrations.RemoveField(model_name="clinvarbgjob", name="case"),
        migrations.RemoveField(model_name="clinvarbgjob", name="clinvarquery"),
        migrations.RemoveField(model_name="clinvarbgjob", name="project"),
        migrations.RemoveField(model_name="clinvarquery", name="case"),
        migrations.RemoveField(model_name="clinvarquery", name="query_results"),
        migrations.RemoveField(model_name="clinvarquery", name="user"),
        migrations.DeleteModel(name="ClinvarBgJob"),
        migrations.DeleteModel(name="ClinvarQuery"),
    ]
