# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-20 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("variants", "0056_add_info_and_distance")]

    operations = [
        migrations.AlterModelOptions(name="casecomments", options={"ordering": ["date_created"]}),
        migrations.AlterField(
            model_name="smallvariantcomment", name="text", field=models.TextField()
        ),
    ]
