# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-04 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("variants", "0059_smallvariantqueryvariantscores_api_result")]

    operations = [
        migrations.RemoveIndex(
            model_name="smallvariantcomment", name="variants_sm_release_961b97_idx"
        ),
        migrations.AlterUniqueTogether(
            name="smallvariantflags",
            unique_together=set(
                [("release", "chromosome", "start", "end", "reference", "alternative", "case")]
            ),
        ),
        migrations.AddIndex(
            model_name="smallvariantcomment",
            index=models.Index(
                fields=[
                    "release",
                    "chromosome",
                    "start",
                    "end",
                    "reference",
                    "alternative",
                    "case",
                ],
                name="variants_sm_release_d0b222_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="smallvariantflags",
            index=models.Index(
                fields=[
                    "release",
                    "chromosome",
                    "start",
                    "end",
                    "reference",
                    "alternative",
                    "case",
                ],
                name="variants_sm_release_66852d_idx",
            ),
        ),
    ]
