# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-27 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("svs", "0012_structuralvariantflags_flag_molecular"),
        ("variants", "0075_projectcasesfilterbgjob_cohort"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="latest_structural_variant_set",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="case_of_latest_structuralvariant_set",
                to="svs.StructuralVariantSet",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="latest_variant_set",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="case_of_latest_variant_set",
                to="variants.SmallVariantSet",
            ),
        ),
    ]
