# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-06 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cohorts", "0004_auto_20200710_1548"),
        ("variants", "0077_set_latest_variant_sets"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportprojectcasesfilebgjob",
            name="cohort",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="cohorts.Cohort"
            ),
        ),
    ]
