# Generated by Django 3.2.7 on 2022-01-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("variants", "0083_auto_20211129_1443"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="release",
            field=models.CharField(default="GRCh37", max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="smallvariantset",
            name="release",
            field=models.CharField(default="GRCh37", max_length=32, null=True),
        ),
    ]
