# Generated by Django 3.2.23 on 2024-02-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("variants", "0095_auto_20230724_0820"),
    ]

    operations = [
        migrations.AddField(
            model_name="impactpresets",
            name="max_exon_dist",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
