# Generated by Django 3.2.23 on 2024-02-08 16:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("variants", "0096_impactpresets_max_exon_dist"),
    ]

    operations = [
        migrations.RunSQL(
            r"""ALTER TABLE "variants_smallvariantqueryresultrow" ALTER COLUMN "id" TYPE bigint USING "id"::bigint""",
            r"""ALTER TABLE "variants_smallvariantqueryresultrow" ALTER COLUMN "id" TYPE integer USING "id"::integer""",
        ),
        migrations.RunSQL(
            r"""ALTER TABLE "variants_smallvariantqueryresultset" ALTER COLUMN "id" TYPE bigint USING "id"::bigint""",
            r"""ALTER TABLE "variants_smallvariantqueryresultset" ALTER COLUMN "id" TYPE integer USING "id"::integer""",
        ),
        migrations.RunSQL(
            r"""ALTER TABLE "variants_smallvariantquery_query_results" ALTER COLUMN "id" TYPE bigint USING "id"::bigint""",
            r"""ALTER TABLE "variants_smallvariantquery_query_results" ALTER COLUMN "id" TYPE integer USING "id"::integer""",
        ),
    ]
