# Generated by Django 3.2.24 on 2024-02-20 16:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("variants", "0097_int_to_bigint"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="acmgcriteriarating",
            options={"ordering": ["chromosome", "start", "reference", "alternative"]},
        ),
    ]
