# Generated by Django 3.2.25 on 2024-05-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("variants", "0102_auto_20240322_1502"),
    ]

    operations = [
        migrations.AddField(
            model_name="presetset",
            name="default_presetset",
            field=models.BooleanField(default=False, help_text="Set as the default preset set"),
        ),
    ]
