# Generated by Django 3.2.25 on 2024-07-15 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("variants", "0106_quickpresets_position"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quickpresets",
            options={"ordering": ("position",)},
        ),
    ]
