# Generated by Django 3.2.25 on 2024-08-07 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("variants", "0107_alter_quickpresets_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clearexpiredexportedfilesbgjob",
            options={"ordering": ("-date_created", "pk")},
        ),
        migrations.AlterModelOptions(
            name="clearinactivevariantsetsbgjob",
            options={"ordering": ("-date_created", "pk")},
        ),
        migrations.AlterModelOptions(
            name="clearoldkioskcasesbgjob",
            options={"ordering": ("-date_created", "pk")},
        ),
        migrations.AlterModelOptions(
            name="exportfilebgjob",
            options={"ordering": ("-date_created", "pk")},
        ),
        migrations.AlterModelOptions(
            name="exportprojectcasesfilebgjob",
            options={"ordering": ("-date_created", "pk")},
        ),
        migrations.AlterModelOptions(
            name="projectcasessmallvariantquery",
            options={"ordering": ("-date_created", "pk")},
        ),
        migrations.AlterModelOptions(
            name="refreshsmallvariantsummarybgjob",
            options={"ordering": ("-date_created", "pk")},
        ),
        migrations.AlterModelOptions(
            name="smallvariantquery",
            options={"ordering": ("-date_created", "pk")},
        ),
        migrations.AlterModelOptions(
            name="smallvariantqueryresultset",
            options={"ordering": ("-date_created", "pk")},
        ),
    ]
