# Generated by Django 4.2.26 on 2025-12-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("variants", "0112_alter_case_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="flagsetcpresets",
            name="clinvar_exclude_conflicting",
            field=models.BooleanField(default=False),
        ),
    ]
