# Generated by Django 4.2.26 on 2026-03-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("variants", "0113_add_clinvar_exclude_conflicting_to_flagsetc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quickpresets",
            name="inheritance",
            field=models.CharField(
                choices=[
                    ("de_novo", "de novo"),
                    ("de_novo_relaxed", "de novo relaxed"),
                    ("dominant", "dominant"),
                    ("homozygous_recessive", "homozygous recessive"),
                    ("compound_heterozygous", "compound heterozygous"),
                    ("recessive", "recessive"),
                    ("x_recessive", "X-recessive"),
                    ("affected_carriers", "affected carriers"),
                    ("any", "any"),
                ],
                default="any",
                help_text="Presets for inheritance",
                max_length=32,
            ),
        ),
    ]
