# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-26 12:43
from __future__ import unicode_literals

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("variants", "0074_caddsubmissionbgjob"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cohort",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, help_text="DateTime of creation"),
                ),
                (
                    "date_modified",
                    models.DateTimeField(auto_now=True, help_text="DateTime of last modification"),
                ),
                (
                    "sodar_uuid",
                    models.UUIDField(
                        default=uuid.uuid4, help_text="Small variant flags SODAR UUID", unique=True
                    ),
                ),
                ("cases", models.ManyToManyField(default=None, to="variants.Case")),
                (
                    "project",
                    models.ForeignKey(
                        help_text="The base project of the cohorts.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cohorts",
                        to="variants.CaseAwareProject",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the cohorts",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cohorts_cohort_related",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["date_modified"],
            },
        ),
    ]
