# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-26 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("cohorts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cohort",
            name="name",
            field=models.CharField(default=django.utils.timezone.now, max_length=512),
            preserve_default=False,
        ),
    ]
