# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-01 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cohorts", "0002_cohort_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cohort",
            options={"ordering": ["-date_modified"]},
        ),
    ]
