# Generated by Django 3.2.16 on 2023-01-02 13:10

from django.db import migrations


def create_through_relations(apps, schema_editor):
    Cohort = apps.get_model("cohorts", "Cohort")
    CohortCase = apps.get_model("cohorts", "CohortCase")
    for cohort in Cohort.objects.all():
        for case in cohort.cases.all():
            CohortCase(
                cohort=cohort,
                case=case,
            ).save()


class Migration(migrations.Migration):
    dependencies = [
        ("cohorts", "0005_auto_20230102_1310"),
    ]

    operations = [
        migrations.RunPython(create_through_relations, reverse_code=migrations.RunPython.noop),
    ]
