# Generated by Django 3.2.25 on 2024-07-15 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0002_auto_20231025_1003"),
    ]

    operations = [migrations.RunSQL("CREATE EXTENSION fuzzystrmatch;")]
