# Generated by Django 3.2.25 on 2024-08-06 14:16

import django.core.serializers.json
from django.db import migrations, models
import django_pydantic_field.fields

import cases.models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0003_add_fuzzy_stringmatching"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAndGlobalSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "user_settings",
                    django_pydantic_field.fields.PydanticSchemaField(
                        config=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        schema=cases.models.UserSettings,
                    ),
                ),
                (
                    "global_settings",
                    django_pydantic_field.fields.PydanticSchemaField(
                        config=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        schema=cases.models.GlobalSettings,
                    ),
                ),
            ],
            options={
                "managed": False,
            },
        ),
    ]
