# Generated by Django 3.2.25 on 2024-08-19 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0004_userandglobalsettings"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="disease",
            options={"ordering": ["term_label", "term_id"]},
        ),
        migrations.AlterModelOptions(
            name="individual",
            options={"ordering": ["date_created", "name"]},
        ),
        migrations.AlterModelOptions(
            name="phenotypicfeature",
            options={"ordering": ["term_label", "term_id"]},
        ),
    ]
