# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-04 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("geneinfo", "0003_auto_20181127_1320")]

    operations = [
        migrations.CreateModel(
            name="NcbiGeneInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("entrez_id", models.CharField(max_length=16)),
                ("summary", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="NcbiGeneRif",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("entrez_id", models.CharField(max_length=16)),
                ("rif_text", models.TextField()),
            ],
        ),
        migrations.AddIndex(
            model_name="ncbigenerif",
            index=models.Index(fields=["entrez_id"], name="geneinfo_nc_entrez__79134c_idx"),
        ),
        migrations.AddIndex(
            model_name="ncbigeneinfo",
            index=models.Index(fields=["entrez_id"], name="geneinfo_nc_entrez__e13b8a_idx"),
        ),
    ]
