# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-19 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("geneinfo", "0005_auto_20190104_1554")]

    operations = [
        migrations.CreateModel(
            name="HpoName",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("hpo_id", models.CharField(max_length=16, null=True)),
                ("name", models.CharField(max_length=512, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name="hponame",
            index=models.Index(fields=["hpo_id"], name="geneinfo_hp_hpo_id_5b82f3_idx"),
        ),
    ]
