# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("geneinfo", "0006_auto_20190319_1638")]

    operations = [
        migrations.CreateModel(
            name="RefseqToHgnc",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("entrez_id", models.CharField(max_length=16)),
                ("hgnc_id", models.CharField(max_length=16)),
            ],
        )
    ]
