# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-08 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("geneinfo", "0007_refseqtohgnc")]

    operations = [
        migrations.CreateModel(
            name="Acmg",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("entrez_id", models.CharField(max_length=16)),
                ("ensembl_gene_id", models.CharField(max_length=32)),
                ("symbol", models.CharField(max_length=32)),
            ],
        )
    ]
