# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-26 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("geneinfo", "0008_acmg")]

    operations = [
        migrations.AddIndex(
            model_name="acmg",
            index=models.Index(fields=["entrez_id"], name="geneinfo_ac_entrez__fa95a2_idx"),
        ),
        migrations.AddIndex(
            model_name="acmg",
            index=models.Index(fields=["ensembl_gene_id"], name="geneinfo_ac_ensembl_f71c79_idx"),
        ),
        migrations.AddIndex(
            model_name="hgnc",
            index=models.Index(fields=["hgnc_id"], name="geneinfo_hg_hgnc_id_e02c9b_idx"),
        ),
        migrations.AddIndex(
            model_name="refseqtohgnc",
            index=models.Index(fields=["entrez_id"], name="geneinfo_re_entrez__98dd58_idx"),
        ),
        migrations.AddIndex(
            model_name="refseqtohgnc",
            index=models.Index(fields=["hgnc_id"], name="geneinfo_re_hgnc_id_5906c2_idx"),
        ),
    ]
