# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-13 13:19
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("geneinfo", "0013_materialized_view_geneidtoinheritance")]

    operations = [
        migrations.CreateModel(
            name="MgiHomMouseHumanSequence",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("homologene_id", models.IntegerField()),
                ("common_organism_name", models.CharField(max_length=32)),
                ("ncbi_taxon_id", models.CharField(max_length=16)),
                ("symbol", models.CharField(max_length=32)),
                ("entrez_id", models.CharField(max_length=16)),
                ("mgi_id", models.CharField(max_length=16, null=True)),
                ("hgnc_id", models.CharField(max_length=16, null=True)),
                ("omim_id", models.CharField(max_length=32, null=True)),
                ("location", models.CharField(max_length=64, null=True)),
                ("coordinates", models.CharField(max_length=128, null=True)),
                (
                    "nucleotide_refseq_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=16), size=None
                    ),
                ),
                (
                    "protein_refseq_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=16), size=None
                    ),
                ),
                (
                    "swissprot_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=16), size=None
                    ),
                ),
            ],
        )
    ]
