# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-13 13:39
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.conf import settings
from django.db import migrations, models


operations = [
    migrations.CreateModel(
        name="MgiMapping",
        fields=[
            (
                "id",
                models.AutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                ),
            ),
            ("hgnc_id", models.CharField(max_length=16, null=True)),
            ("omim_id", models.CharField(max_length=32, null=True)),
            ("human_coordinates", models.CharField(max_length=128, null=True)),
            ("human_entrez_id", models.CharField(max_length=16, null=True)),
            (
                "human_nucleotide_refseq_ids",
                django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(max_length=16), size=None
                ),
            ),
            (
                "human_protein_refseq_ids",
                django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(max_length=16), size=None
                ),
            ),
            (
                "human_swissprot_ids",
                django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(max_length=16), size=None
                ),
            ),
            ("mgi_id", models.CharField(max_length=16, null=True)),
            ("mouse_coordinates", models.CharField(max_length=128, null=True)),
            ("mouse_entrez_id", models.CharField(max_length=16, null=True)),
            (
                "mouse_nucleotide_refseq_ids",
                django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(max_length=16), size=None
                ),
            ),
            (
                "mouse_protein_refseq_ids",
                django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(max_length=16), size=None
                ),
            ),
            (
                "mouse_swissprot_ids",
                django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(max_length=16), size=None
                ),
            ),
        ],
        options={"db_table": "geneinfo_mgimapping", "managed": settings.IS_TESTING},
    )
]


if not settings.IS_TESTING:
    operations.append(
        migrations.RunSQL(
            """
            CREATE MATERIALIZED VIEW geneinfo_mgimapping
            AS
                SELECT
                    human.hgnc_id,
                    human.omim_id,
                    human.coordinates AS human_coordinates,
                    human.entrez_id AS human_entrez_id,
                    human.symbol AS human_symbol,
                    human.nucleotide_refseq_ids AS human_nucleotide_refseq_ids,
                    human.protein_refseq_ids AS human_protein_refseq_ids,
                    human.swissprot_ids AS human_swissprot_ids,
                    mouse.mgi_id,
                    mouse.coordinates AS mouse_coordinates,
                    mouse.entrez_id AS mouse_entrez_id,
                    mouse.symbol AS mouse_symbol,
                    mouse.nucleotide_refseq_ids AS mouse_nucleotide_refseq_ids,
                    mouse.protein_refseq_ids AS mouse_protein_refseq_ids,
                    mouse.swissprot_ids AS mouse_swissprot_ids
                FROM
                    geneinfo_mgihommousehumansequence human
                    LEFT OUTER JOIN LATERAL (
                        SELECT
                            *
                        FROM
                            geneinfo_mgihommousehumansequence
                        WHERE
                            human.homologene_id = homologene_id
                            AND ncbi_taxon_id = '10090'
                    ) mouse ON TRUE
                WHERE
                    human.ncbi_taxon_id = '9606'
            WITH DATA;
            """,
            """
            DROP MATERIALIZED VIEW geneinfno_mgimapping;
            """,
        )
    )


class Migration(migrations.Migration):

    dependencies = [("geneinfo", "0014_mgihommousehumansequence")]

    operations = operations
