# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-13 13:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations

if not settings.IS_TESTING:
    operations = [
        migrations.RunSQL(
            "CREATE INDEX geneinfo_mgimapping_human_entrez_id_idx ON geneinfo_mgimapping (human_entrez_id);"
        )
    ]
else:
    operations = []


class Migration(migrations.Migration):

    dependencies = [("geneinfo", "0015_mgimapping")]

    operations = operations
