# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-18 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("geneinfo", "0019_ncbigenerif_pubmed_ids")]

    operations = [
        migrations.AddIndex(
            model_name="hponame",
            index=models.Index(fields=["name"], name="geneinfo_hp_name_922635_idx"),
        )
    ]
