# Generated by Django 3.2.7 on 2021-10-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geneinfo", "0024_alter_ncbigenerif_pubmed_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="hgnc",
            name="agr",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="hgnc",
            name="lncipedia",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="hgnc",
            name="mane_select",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
