# Generated by Django 3.2.7 on 2021-10-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geneinfo", "0025_auto_20211019_0829"),
    ]

    operations = [
        migrations.AddField(
            model_name="hgnc",
            name="gtrnadb",
            field=models.CharField(max_length=32, null=True),
        ),
    ]
