# Generated by Django 4.2.20 on 2025-05-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("importer", "0012_alter_importcasebgjob_bg_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caseimportinfo",
            name="status",
            field=models.CharField(
                choices=[
                    ("initial", "initial"),
                    ("active", "active"),
                    ("closed-unsolved", "closed as unsolved"),
                    ("closed-uncertain", "closed as uncertain"),
                    ("closed-partially-solved", "closed as partially solved"),
                    ("closed-solved", "closed as solved"),
                ],
                default="initial",
                max_length=32,
            ),
        ),
    ]
