from django.urls import path

from cases import views, views_ajax, views_api

app_name = "cases"
ui_urlpatterns = [
    path(
        route="vueapp/<uuid:project>/",
        view=views.EntrypointView.as_view(),
        name="entrypoint",
    ),
]

ajax_urlpatterns = [
    path(
        route="ajax/case/list/<uuid:project>/",
        view=views_ajax.CaseListAjaxView.as_view(),
        name="ajax-case-list",
    ),
    path(
        route="ajax/case/retrieve-update-destroy/<uuid:case>/",
        view=views_ajax.CaseRetrieveUpdateDestroyAjaxView.as_view(),
        name="ajax-case-retrieveupdatedestroy",
    ),
    path(
        route="ajax/case-comment/list-create/<uuid:case>/",
        view=views_ajax.CaseCommentListCreateAjaxView.as_view(),
        name="ajax-casecomment-listcreate",
    ),
    path(
        route="ajax/case-comment/retrieve-update-destroy/<uuid:casecomment>/",
        view=views_ajax.CaseCommentRetrieveUpdateDestroyAjaxView.as_view(),
        name="ajax-casecomment-retrieveupdatedestroy",
    ),
    path(
        route="ajax/case-phenotype-terms/list-create/<uuid:case>/",
        view=views_ajax.CasePhenotypeTermsListCreateAjaxView.as_view(),
        name="ajax-casephenotypeterms-listcreate",
    ),
    path(
        route="ajax/case-phenotype-terms/retrieve-update-destroy/<uuid:casephenotypeterms>/",
        view=views_ajax.CasePhenotypeTermsRetrieveUpdateDestroyAjaxView.as_view(),
        name="ajax-casephenotypeterms-retrieveupdatedestroy",
    ),
    path(
        route="ajax/annotation-release-info/list/<uuid:case>/",
        view=views_ajax.AnnotationReleaseInfoAjaxView.as_view(),
        name="ajax-annotationreleaseinfo-list",
    ),
    path(
        route="ajax/sv-annotation-release-info/list/<uuid:case>/",
        view=views_ajax.SvAnnotationReleaseInfoAjaxView.as_view(),
        name="ajax-svannotationreleaseinfo-list",
    ),
    path(
        route="ajax/case-gene-annotation/list/<uuid:case>/",
        view=views_ajax.CaseGeneAnnotationListAjaxView.as_view(),
        name="ajax-casegeneannotation-list",
    ),
    path(
        route="ajax/user-permissions/<uuid:project>/",
        view=views_ajax.ProjectUserPermissionsAjaxView.as_view(),
        name="ajax-userpermissions",
    ),
    path(
        route="ajax/case-alignment-stats/list/<uuid:case>/",
        view=views_ajax.CaseAlignmentStatsListAjaxView.as_view(),
        name="ajax-casealignmentstats-list",
    ),
    path(
        route="ajax/case-variant-stats/list/<uuid:case>/",
        view=views_ajax.SampleVariantStatisticsListAjaxView.as_view(),
        name="ajax-casevariantstats-list",
    ),
    path(
        route="ajax/case-relatedness/list/<uuid:case>/",
        view=views_ajax.PedigreeRelatednessListAjaxView.as_view(),
        name="ajax-caserelatedness-list",
    ),
]

api_urlpatterns = [
    path(
        route="api/case/count/<uuid:project>/",
        view=views_api.CaseCountApiView.as_view(),
        name="api-case-count",
    ),
    path(
        route="api/case/list/<uuid:project>/",
        view=views_api.CaseListApiView.as_view(),
        name="api-case-list",
    ),
    path(
        route="api/case/retrieve-update-destroy/<uuid:case>/",
        view=views_api.CaseRetrieveUpdateDestroyApiView.as_view(),
        name="api-case-retrieveupdatedestroy",
    ),
    path(
        route="api/case-comment/list-create/<uuid:case>/",
        view=views_api.CaseCommentListCreateApiView.as_view(),
        name="api-casecomment-listcreate",
    ),
    path(
        route="ajax/case-comment/retrieve-update-destroy/<uuid:casecomment>/",
        view=views_api.CaseCommentRetrieveUpdateDestroyApiView.as_view(),
        name="api-casecomment-retrieveupdatedestroy",
    ),
    path(
        route="api/case-phenotype-terms/list-create/<uuid:case>/",
        view=views_api.CasePhenotypeTermsListCreateApiView.as_view(),
        name="api-casephenotypeterms-listcreate",
    ),
    path(
        route="api/case-phenotype-terms/retrieve-update-destroy/<uuid:casephenotypeterms>/",
        view=views_api.CasePhenotypeTermsRetrieveUpdateDestroyApiView.as_view(),
        name="api-casephenotypeterms-retrieveupdatedestroy",
    ),
    path(
        route="api/annotation-release-info/list/<uuid:case>/",
        view=views_api.AnnotationReleaseInfoApiView.as_view(),
        name="api-annotationreleaseinfo-list",
    ),
    path(
        route="api/sv-annotation-release-info/list/<uuid:case>/",
        view=views_api.SvAnnotationReleaseInfoApiView.as_view(),
        name="api-svannotationreleaseinfo-list",
    ),
    path(
        route="api/case-gene-annotation/list/<uuid:case>/",
        view=views_ajax.CaseGeneAnnotationListAjaxView.as_view(),
        name="api-casegeneannotation-list",
    ),
    path(
        route="api/case-alignment-stats/list/<uuid:case>/",
        view=views_ajax.CaseAlignmentStatsListAjaxView.as_view(),
        name="api-casealignmentstats-list",
    ),
    path(
        route="api/case-variant-stats/list/<uuid:case>/",
        view=views_ajax.SampleVariantStatisticsListAjaxView.as_view(),
        name="api-casevariantstats-list",
    ),
    path(
        route="api/case-relatedness/list/<uuid:case>/",
        view=views_ajax.PedigreeRelatednessListAjaxView.as_view(),
        name="api-caserelatedness-list",
    ),
    path(
        route="api/user-and-global-settings/",
        view=views_api.UserAndGlobalSettingsView.as_view(),
        name="api-userandglobalsettings",
    ),
]


urlpatterns = ui_urlpatterns + ajax_urlpatterns + api_urlpatterns
