name: Check Mandatory Trailers

on:
  - pull_request

jobs:
  check-mandatory-trailers:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: print history
        run: |
          set -x
          echo ${{ github.event.pull_request.base.ref || github.ref }}
          echo ${{ github.event.pull_request.head.ref || github.ref }}
