
name: Dependencies report

on:
  pull_request:

jobs:
  build:
    name:  Dependencies report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: deps-report
        uses: MeilleursAgents/deps-report@master
        with:
          file: backend/Pipfile.lock
          github_token: ${{ secrets.GITHUB_TOKEN }}
