# Generated by Django 3.2.16 on 2022-10-29 17:27

import uuid

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projectroles", "0020_project_has_public_children"),
    ]

    operations = [
        migrations.CreateModel(
            name="VarAnnoSet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, help_text="DateTime of creation"),
                ),
                (
                    "date_modified",
                    models.DateTimeField(auto_now=True, help_text="DateTime of last modification"),
                ),
                (
                    "sodar_uuid",
                    models.UUIDField(
                        default=uuid.uuid4, help_text="Cohort SODAR UUID", unique=True
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The variant annotation set's title.", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="An optional description for the variant annotation set.",
                        null=True,
                    ),
                ),
                (
                    "release",
                    models.CharField(
                        choices=[("GRCh37", "GRCh37"), ("GRCh38", "GRCh38")],
                        help_text="Genome build of the variant annotation set.",
                        max_length=16,
                    ),
                ),
                (
                    "fields",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=64),
                        help_text="The allowed fields in the entries.",
                        size=None,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="projectroles.project"
                    ),
                ),
            ],
            options={
                "ordering": ("title",),
            },
        ),
        migrations.CreateModel(
            name="VarAnnoSetEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, help_text="DateTime of creation"),
                ),
                (
                    "date_modified",
                    models.DateTimeField(auto_now=True, help_text="DateTime of last modification"),
                ),
                (
                    "sodar_uuid",
                    models.UUIDField(
                        default=uuid.uuid4, help_text="Cohort SODAR UUID", unique=True
                    ),
                ),
                ("release", models.CharField(max_length=32)),
                ("chromosome", models.CharField(max_length=32)),
                ("start", models.IntegerField()),
                ("end", models.IntegerField()),
                ("reference", models.CharField(max_length=512)),
                ("alternative", models.CharField(max_length=512)),
                (
                    "payload",
                    models.JSONField(
                        help_text="The annotation's data with fields defined in the variant annotation set."
                    ),
                ),
                (
                    "varannoset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="varannos.varannoset"
                    ),
                ),
            ],
            options={
                "ordering": ("release", "chromosome", "start", "reference", "alternative"),
            },
        ),
        migrations.AddIndex(
            model_name="varannosetentry",
            index=models.Index(
                fields=["release", "chromosome", "start", "reference", "alternative"],
                name="varannos_va_release_09c50d_idx",
            ),
        ),
    ]
